import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// The full DolyOutfits POS data model.
// Money is always integer cents (v.number(), validated at the service layer).
// Dates are epoch ms; day buckets (receivedDay / spentDay) are YYYY-MM-DD
// strings computed in the shop timezone.

export default defineSchema({
  // Single-row shop settings. Schema stays tenant-ready for multi-tenant later.
  shop: defineTable({
    name: v.string(),
    logoStorageId: v.optional(v.id("_storage")),
    address: v.optional(v.string()),
    phone: v.optional(v.string()), // shown as the sender on printed invoices
    currency: v.string(), // base currency code, e.g. "USD"
    exchangeRate: v.number(), // e.g. 4000 riel per 1 USD — owner-stored, used to convert
    timezone: v.string(), // e.g. "Asia/Phnom_Penh"
    deliveryEnabled: v.boolean(),
    lowStockThreshold: v.optional(v.number()),
    language: v.union(v.literal("en"), v.literal("km")),
    printerConfig: v.optional(
      v.object({
        type: v.union(v.literal("webusb"), v.literal("qz_tray"), v.literal("network")),
        vendorId: v.optional(v.number()),
        productId: v.optional(v.number()),
        // T25 — QZ Tray: the OS printer name and the public signing
        // certificate generated by QZ Site Manager (digital-certificate.txt;
        // the private key stays in QZ Tray on the owner's computer).
        qzPrinterName: v.optional(v.string()),
        qzCert: v.optional(v.string()),
        networkHost: v.optional(v.string()),
        networkPort: v.optional(v.number()),
      })
    ),
    // Preselected on the POS sale screen; unset falls back to the walk-in customer.
    defaultCustomerId: v.optional(v.id("customers")),
  }),

  // Staff linked to better-auth users. Role is `owner` | `staff` today.
  users: defineTable({
    authUserId: v.string(), // the better-auth component user _id
    name: v.string(),
    email: v.string(),
    role: v.union(v.literal("owner"), v.literal("staff")),
    phone: v.optional(v.string()),
    active: v.boolean(),
  })
    .index("by_authUserId", ["authUserId"])
    .index("by_email", ["email"]),

  categories: defineTable({
    name: v.string(),
    nameLower: v.string(), // lowercased copy — case-insensitive prefix search on the index
    active: v.boolean(), // soft-delete only: nothing is ever hard-deleted
  }).index("by_nameLower", ["nameLower"]),

  // The shop's selling pages. Every sale has exactly one.
  salesChannels: defineTable({
    name: v.string(),
    nameLower: v.string(), // case-insensitive prefix search
    type: v.union(
      v.literal("facebook"),
      v.literal("instagram"),
      v.literal("tiktok"),
      v.literal("walk_in"),
      v.literal("custom")
    ),
    active: v.boolean(),
  }).index("by_nameLower", ["nameLower"]),

  // One product = one design. Sizes always exist; colors are optional.
  products: defineTable({
    name: v.string(),
    nameLower: v.string(), // lowercased copy — case-insensitive prefix search on the index
    description: v.optional(v.string()),
    code: v.optional(v.string()), // owner's product code, shown on POS cards next to the SKU
    categoryId: v.optional(v.id("categories")),
    defaultPrice: v.number(), // sell price, integer cents
    defaultCost: v.number(), // reference cost, integer cents (prefills purchase cost)
    hasColors: v.boolean(),
    sizes: v.array(v.string()),
    colors: v.array(v.string()), // [] when hasColors is false
    imageStorageId: v.optional(v.id("_storage")),
    active: v.boolean(), // soft-delete only
  })
    .index("by_nameLower", ["nameLower"])
    .index("by_category_nameLower", ["categoryId", "nameLower"]),

  // One row per size x color combo. price/cost override the product defaults
  // when present; the rest fall back to the product's default price/cost.
  // active=false when the owner removes a size/color — rows stay for the
  // stock ledger's trace (soft-delete only, nothing is ever hard-deleted).
  productVariants: defineTable({
    productId: v.id("products"),
    size: v.string(),
    color: v.optional(v.string()),
    price: v.optional(v.number()), // override, integer cents
    cost: v.optional(v.number()), // override, integer cents
    sku: v.optional(v.string()),
    active: v.boolean(),
  })
    .index("by_product", ["productId"])
    .index("by_product_size", ["productId", "size"])
    .index("by_sku", ["sku"])
    .index("by_size_active", ["size", "active"]),

  suppliers: defineTable({
    name: v.string(),
    nameLower: v.string(),
    phone: v.optional(v.string()),
    notes: v.optional(v.string()),
    active: v.boolean(),
  }).index("by_nameLower", ["nameLower"]),

  // Contact records only — companies never log in or use the app.
  deliveryCompanies: defineTable({
    name: v.string(),
    nameLower: v.string(), // case-insensitive prefix search
    phone: v.optional(v.string()),
    defaultFee: v.number(), // what the shop pays per handled order, integer cents
    imageStorageId: v.optional(v.id("_storage")), // logo, shown in the POS picker
    active: v.boolean(),
  }).index("by_nameLower", ["nameLower"]),

  // Editable at any time. Stock enters via ledger rows owned by purchaseItems.
  // purchasedAt is the business (purchase) date; receivedAt the arrival date
  // (present = stock is in).
  purchases: defineTable({
    supplierId: v.id("suppliers"),
    code: v.string(), // human-friendly display label, not an access key
    status: v.union(v.literal("draft"), v.literal("received")),
    purchasedAt: v.number(), // business date, epoch ms
    receivedAt: v.optional(v.number()),
    notes: v.optional(v.string()),
    deliveryCost: v.optional(v.number()), // what transport cost us, integer cents
    otherCost: v.optional(v.number()), // any other purchase cost, integer cents
    userId: v.id("users"),
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_createdAt", ["createdAt"])
    .index("by_supplier", ["supplierId"])
    .index("by_code", ["code"])
    // "Purchases received in range" (dashboard + reports) — receivedAt is
    // optional (drafts have none); the range query rides this index directly.
    .index("by_receivedAt", ["receivedAt"]),

  purchaseItems: defineTable({
    purchaseId: v.id("purchases"),
    variantId: v.id("productVariants"),
    qty: v.number(),
    unitCost: v.number(), // integer cents
  })
    .index("by_purchase", ["purchaseId"])
    .index("by_variant", ["variantId"]),

  // IMMUTABLE movement rows. Stock = sum(delta) per variant — no stored totals.
  stockLedger: defineTable({
    variantId: v.id("productVariants"),
    delta: v.number(), // + in, − out
    reason: v.union(
      v.literal("purchase"),
      v.literal("sale"),
      v.literal("return"),
      v.literal("exchange_out"), // old item removed from the order, back to shelf
      v.literal("exchange_in"), // new item added to the order, leaves shelf
      v.literal("cancel"),
      v.literal("adjustment"),
      v.literal("stocktake")
    ),
    purchaseItemId: v.optional(v.id("purchaseItems")),
    saleItemId: v.optional(v.id("saleItems")),
    userId: v.id("users"),
    ts: v.number(),
    note: v.optional(v.string()),
  })
    .index("by_variant_ts", ["variantId", "ts"])
    .index("by_reason_ts", ["reason", "ts"])
    // Purchase edits rewrite only this line's rows — reachable by ownership.
    .index("by_purchaseItem", ["purchaseItemId"])
    // T21 — the stock movement report scans a date range across all variants.
    .index("by_ts", ["ts"]),

  customers: defineTable({
    name: v.string(),
    nameLower: v.string(), // case-insensitive prefix search
    phone: v.string(), // normalized (digits only, no leading zeros) — unique per shop
    address: v.optional(v.string()),
    notes: v.optional(v.string()),
    active: v.boolean(),
    isWalkIn: v.optional(v.boolean()), // the seeded "Walk-in Customer" record — the POS default
  })
    .index("by_phone", ["phone"])
    .index("by_nameLower", ["nameLower"])
    .index("by_isWalkIn", ["isWalkIn"]),

  // One order per sale. Drafts touch no stock — deduction happens on confirm;
  // `pending` is a post-confirm regression (stock stays out while the order
  // waits), never a checkout status.
  sales: defineTable({
    code: v.string(), // e.g. "20261001-001" — display label, never an access key
    customerId: v.id("customers"),
    salesChannelId: v.id("salesChannels"),
    deliveryCompanyId: v.optional(v.id("deliveryCompanies")), // null when delivery off / self-delivery
    status: v.union(
      v.literal("draft"),
      v.literal("pending"),
      v.literal("confirmed"),
      v.literal("packed"),
      v.literal("delivering"),
      v.literal("delivered"),
      v.literal("partially_delivered"),
      v.literal("cancelled")
    ),
    deliveryFee: v.number(), // charged to the customer, integer cents
    deliveryCost: v.number(), // paid to the delivery company, integer cents
    discount: v.number(), // order-level discount, integer cents
    userId: v.id("users"), // staff who created the order
    createdAt: v.number(),
    deliveredAt: v.optional(v.number()),
    note: v.optional(v.string()),
    // T17 — evening delivery reconciliation: the outcome the owner marked for
    // this order (how the delivery actually ended) and when they marked it.
    // `imageStorageId` is the packaging photo shot before the package left.
    deliveryOutcome: v.optional(
      v.union(
        v.literal("delivered"),
        v.literal("partial"),
        v.literal("returned"),
        v.literal("cancelled")
      )
    ),
    outcomeMarkedAt: v.optional(v.number()),
    imageStorageId: v.optional(v.id("_storage")),
    // The package went out and the trip happened, but the customer refused
    // the goods: cancelling normally wipes the whole bill, so this flag keeps
    // the shipping fee owed (ticked by the owner at cancel time). Absent on
    // every order cancelled before the flag existed — those owe nothing, so
    // history never changes.
    chargeDeliveryOnCancel: v.optional(v.boolean()),
    // Bumped by every saveEdit — the stale-edit guard (a save whose version
    // no longer matches is rejected, so concurrent edits never overwrite).
    editedVersion: v.optional(v.number()),
  })
    .index("by_createdAt", ["createdAt"])
    .index("by_status_createdAt", ["status", "createdAt"])
    .index("by_customer", ["customerId"])
    .index("by_customer_createdAt", ["customerId", "createdAt"])
    .index("by_channel", ["salesChannelId"])
    .index("by_company", ["deliveryCompanyId"])
    .index("by_user", ["userId"])
    .index("by_code", ["code"])
    .index("by_outcomeMarkedAt", ["outcomeMarkedAt"])
    .index("by_deliveredAt", ["deliveredAt"]),

  // Line-level status so ONE order can mix delivered / cancelled / exchanged.
  saleItems: defineTable({
    saleId: v.id("sales"),
    variantId: v.id("productVariants"),
    unitPrice: v.number(), // integer cents at sale time
    unitCostSnapshot: v.number(), // weighted-average cost at sale time, integer cents
    qtyOrdered: v.number(),
    qtyDelivered: v.number(),
    qtyCancelled: v.number(),
    qtyReturned: v.number(),
    discount: v.optional(v.number()), // per-item discount, integer cents
    // A RAISE (saveEdit) never rewrites the original line: the extra pieces
    // become their OWN internal row pointing back at it. The edit page shows
    // them folded into the parent (getEditData merges), and saveEdit measures
    // quantities against the parent's EFFECTIVE billed total (this row +
    // every split row), so re-saving the same displayed quantity is a no-op.
    splitFromItemId: v.optional(v.id("saleItems")),
  })
    .index("by_sale", ["saleId"])
    .index("by_variant", ["variantId"]),

  // Manual staff entry only (no gateway). Negative amount = refund (money out).
  payments: defineTable({
    saleId: v.id("sales"),
    amount: v.number(), // integer cents; negative for refunds
    receivedAt: v.number(),
    receivedDay: v.string(), // YYYY-MM-DD in shop tz — indexed so daily reports never full-scan
    method: v.union(
      v.literal("cash"),
      v.literal("bank_transfer"),
      v.literal("other"),
      v.literal("refund")
    ),
    userId: v.id("users"),
    note: v.optional(v.string()),
  })
    .index("by_receivedDay", ["receivedDay"])
    .index("by_sale", ["saleId"]),

  expenseCategories: defineTable({
    name: v.string(),
    nameLower: v.string(),
    active: v.boolean(),
  }).index("by_nameLower", ["nameLower"]),

  expenses: defineTable({
    amount: v.number(), // integer cents
    category: v.string(),
    categoryLower: v.string(), // lowercased copy — case-insensitive prefix search on the index
    spentAt: v.number(),
    spentDay: v.string(), // YYYY-MM-DD in shop tz
    note: v.optional(v.string()),
    userId: v.id("users"),
  })
    .index("by_spentDay", ["spentDay"])
    .index("by_categoryLower", ["categoryLower"]),

  // Immutable per-sale audit history. Every change appends a row.
  saleEvents: defineTable({
    saleId: v.id("sales"),
    type: v.string(), // e.g. "status_changed", "item_exchanged", "price_changed"
    summary: v.string(), // human-readable, plain language for the event list
    payload: v.optional(v.record(v.string(), v.string())), // old → new values for display
    userId: v.id("users"),
    ts: v.number(),
  }).index("by_sale_ts", ["saleId", "ts"]),

  // One key is scoped to the authenticated staff member and exact operation.
  idempotencyRecords: defineTable({
    userId: v.id("users"),
    operation: v.union(
      v.literal("sales.checkout"),
      v.literal("sales.saveEdit"),
      v.literal("purchases.create"),
      v.literal("payments.receive"),
      v.literal("payments.refund"),
      v.literal("adjustments.adjustStock")
    ),
    key: v.string(),
    requestHash: v.string(),
    result: v.union(
      v.object({ kind: v.literal("sale"), id: v.id("sales") }),
      v.object({ kind: v.literal("purchase"), id: v.id("purchases") }),
      v.object({ kind: v.literal("payment"), id: v.id("payments") }),
      v.object({ kind: v.literal("stockLedger"), id: v.id("stockLedger") })
    ),
    createdAt: v.number(),
  }).index("by_scope", ["userId", "operation", "key"]),
});
