// Every user-facing string lives here — plain shop language only, never
// technical terms. Change wording in ONE place. Khmer or English per the
// shop's language setting.

export type Language = "en" | "km";

export const labels = {
  en: {
    appName: "POS",
    nav: {
      dashboard: "Dashboard",
      sales: "Sales",
      products: "Products",
      categories: "Categories",
      customers: "Customers",
      stock: "Stock",
      adjustments: "Adjustments",
      purchases: "Purchases",
      suppliers: "Suppliers",
      delivery: "Delivery Companies",
      deliveryReport: "Delivery Report",
      channels: "Sales Pages",
      expenses: "Expenses",
      reports: "Reports",
      settings: "Shop Settings",
      more: "More",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      search: "Search",
      actions: "Actions",
      active: "Active",
      inactive: "Inactive",
      confirm: "Confirm",
      back: "Back",
      total: "Total",
      note: "Note",
      name: "Name",
      phone: "Phone",
      address: "Address",
      date: "Date",
      email: "Email",
      role: "Role",
      yes: "Yes",
      no: "No",
      close: "Close",
      filter: "Filter",
      rowsPerPage: "Rows per page",
      page: "Page",
      of: "of",
      noResults: "No records found",
      loading: "Loading…",
      optional: "optional",
      required: "Required",
      roleOwner: "Owner",
      roleStaff: "Staff",
      signOut: "Sign out",
      columns: "Columns",
      showAll: "Show all",
      comingSoon: "Coming soon",
      useTyped: 'Use "{value}"',
      more: "Show more",
      lightMode: "Light mode",
      darkMode: "Dark mode",
      // Global AppHeader controls
      pos: "POS",
      profile: "Profile",
      appearance: "Appearance",
      themeSystem: "System",
      enterFullscreen: "Enter fullscreen",
      exitFullscreen: "Exit fullscreen",
      language: "Language",
      languageEnglish: "English",
      languageKhmer: "Khmer",
      expandSidebar: "Expand sidebar",
      collapseSidebar: "Collapse sidebar",
    },
    status: {
      draft: "Draft",
      confirmed: "Confirmed",
      pending: "Pending",
      packed: "Packed",
      delivering: "Out for delivery",
      delivered: "Delivered",
      partially_delivered: "Partially delivered",
      cancelled: "Cancelled",
      received: "Received",
    },
    errors: {
      UNAUTHORIZED: "Please sign in again.",
      FORBIDDEN: "Only the owner can do this.",
      NO_SHOP: "Please finish the shop setup first.",
      NO_STAFF_RECORD: "Your account is not set up for this shop yet.",
      INVALID_MONEY: "Please enter a valid amount.",
      INVALID_QTY: "Please enter a valid quantity.",
      INVALID_DELTA: "Please enter a valid quantity.",
      INVALID_INPUT: "Please check the highlighted fields.",
      CANNOT_CHANGE_OWN_ROLE: "You can't change your own role here.",
      CANNOT_DEACTIVATE_SELF: "You can't deactivate your own account.",
      CANNOT_RESET_OWN_PASSWORD:
        "Use change password for your own account.",
      NOT_FOUND: "Record not found.",
      DUPLICATE_CUSTOMER: "A customer with this phone already exists.",
      DUPLICATE_EMAIL: "That email already has an account.",
      OUT_OF_STOCK: "Not enough stock for this item.",
      EMPTY_CART: "Cart is empty — add at least one item.",
      INVALID_PAYMENT: "Payment must be between 0 and the order total.",
      IDEMPOTENCY_CONFLICT:
        "This save was already submitted with different details. Review and submit again.",
      INVALID_IDEMPOTENCY_KEY: "This save could not be identified. Refresh and try again.",
      // saveEdit's stale-edit guard (the order changed in another window).
      STALE_EDIT: "This order changed in another window. Reload and try again.",
      // Sale lifecycle guards — returns are bounded by what the customer
      // still holds, a delivered order's lines are locked, and delivered
      // can't be marked below what was returned.
      RETURN_EXCEEDS_HELD: "Can't return more than the customer currently has.",
      DELIVERED_BELOW_RETURNED: "Can't mark fewer delivered than were returned.",
      DELIVERED_LOCKED_LINES:
        "This order is delivered — item changes go through the return and exchange flows.",
      CANNOT_CANCEL_HELD:
        "Some pieces are still with the customer — return or correct them before cancelling.",
      GENERIC: "Something went wrong. Please try again.",
      // T25 printing
      PRINT_NO_PRINTER: "No printer is set up yet. Open Settings and set one up.",
      PRINT_FAILED: "Printing failed — check the printer and try again.",
      PRINT_USB_UNSUPPORTED: "USB printing needs Chrome or Edge on a secure connection.",
      PRINT_NO_USB_DEVICE: "USB printer not found. Plug it in and pick it again in Settings.",
      PRINT_USB_DENIED: "USB access was not allowed. Approve the printer when the browser asks.",
      PRINT_USB_BUSY:
        "Windows would not give this printer to the browser (another driver is using it). Unplug and replug it, or switch to QZ Tray or Network mode in Settings.",
      PRINT_QZ_OFFLINE: "QZ Tray is not running. Open QZ Tray on this computer and try again.",
      PRINT_QZ_CONFIG: "QZ Tray setup is incomplete. Check the printer name and certificate in Settings.",
    },
    settings: {
      shopTitle: "Shop details",
      shopHint: "Name, money and time — every report uses these.",
      shopName: "Shop name",
      currency: "Currency",
      currencyHint: "3-letter code, e.g. USD or KHR.",
      timezone: "Timezone",
      timezoneSearch: "Type to search…",
      language: "Language",
      languageHint: "Labels across the app.",
      deliveryEnabled: "Delivery module",
      deliveryHint:
        "On = orders go out with delivery companies. Off = in-store pickup or your own delivery.",
      address: "Address",
      addressHint: "Shown on printed invoices.",
      exchangeRate: "Exchange rate",
      exchangeRateHint: "Local money per 1 unit of your currency. 1 = no conversion.",
      lowStockThreshold: "Low stock warning",
      lowStockThresholdHint: "Warn when a size's stock is at or below this number.",
      defaultCustomer: "Default customer",
      defaultCustomerHint:
        "Picked automatically when the sale page opens. Leave empty to use Walk-in Customer.",
      saved: "Settings saved.",
      usersTitle: "Team",
      usersHint: "Everyone who can sign in to this shop.",
      userActive: "Active",
      userInactive: "Deactivated",
      resetPassword: "Reset password",
      resetPasswordHint:
        "Set a new password for this staff member — they'll use it at their next sign-in.",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      resetPasswordDone: "Password updated.",
      addStaff: "Add staff",
      addStaffHint:
        "Create the sign-in here — share the email and starting password with them; they can change it later.",
      staffName: "Full name",
      staffEmail: "Email",
      startPassword: "Starting password",
      staffCreated: "{name} added — they can sign in now.",
      deactivateTitle: "Deactivate this staff member?",
      deactivateBody:
        "They immediately lose access to the shop. Their past orders and stock movements stay intact, and you can reactivate them any time.",
      deactivateConfirm: "Deactivate",
      activateConfirm: "Reactivate",
      changeRole: "Role",
      ownRoleHint: "You can't change your own role here.",
      notOwnerTitle: "Only the shop owner can open settings",
      notOwnerBody: "Sign in with the owner account to change these.",
      backupTitle: "Data backup",
      backupHint:
        "Download every table in this shop as one JSON file. Keep it somewhere safe — it is your copy of the business records.",
      backupAction: "Download backup",
      backupDone: "Backup downloaded — {n} tables.",
      // T25 printing
      printerTitle: "Receipt printer",
      printerHint:
        "The 80mm thermal printer for receipts and package labels. The A5 invoice always prints through the browser's print dialog, where you can pick any printer.",
      printerType: "Connection",
      printerNone: "No thermal printer",
      printerWebUsb: "USB printer (WebUSB)",
      printerQzTray: "QZ Tray (USB / network / wireless)",
      printerNetwork: "Network printer (IP)",
      printerTypeHint: "How the app reaches the 80mm printer.",
      printerVendorId: "Vendor ID (hex)",
      printerProductId: "Product ID (hex)",
      printerIdsHint: "Filled automatically by the scan button — normally you never type these.",
      printerScan: "Scan USB printer",
      printerScanHint: "Plug the printer in, tap scan, and pick it from the list the browser shows.",
      printerScanDone: "USB printer connected — press Save to keep it.",
      printerQzName: "Printer name",
      printerQzNameHint: "The printer's name exactly as QZ Tray shows it.",
      printerQzCert: "QZ certificate",
      printerQzCertHint:
        "In QZ Tray: Advanced → Site Manager → create a certificate, then paste the contents of digital-certificate.txt here.",
      printerNetworkHost: "Printer IP address",
      printerNetworkHostHint:
        "Must be on the same local network as the app server (the computer running the app).",
      printerNetworkPort: "Port",
      printerNetworkPortHint: "Usually 9100.",
      printerTest: "Test print",
      printerTestDone: "Sent to the printer — check the paper.",
      printerPaperHint:
        "Thermal paper prints with English letters only — Khmer script is not supported by these printers.",
      printTestOk: "Printer test - OK",
    },
    categories: {
      addCategory: "Add Category",
      searchPlaceholder: "Search by name…",
      nameHint: "e.g. Shirts, Dresses, Jeans",
      created: "Category added.",
      saved: "Category saved.",
      newTitle: "New Category",
      editTitle: "Edit Category",
      activeHint: "Turn off to hide this category when adding products.",
      notFoundTitle: "Category not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
    },
    suppliers: {
      addSupplier: "Add Supplier",
      searchPlaceholder: "Search by name…",
      nameHint: "e.g. Phnom Penh Garment",
      phone: "Phone",
      phoneHint: "Optional. Used when calling or texting.",
      notes: "Notes",
      notesHint: "Payment terms, delivery days, anything to remember.",
      created: "Supplier added.",
      saved: "Supplier saved.",
      newTitle: "New Supplier",
      editTitle: "Edit Supplier",
      activeHint: "Turn off to hide this supplier when choosing on a purchase.",
      notFoundTitle: "Supplier not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
    },
    expenses: {
      addExpense: "Add Expense",
      searchPlaceholder: "Search by category…",
      amount: "Amount",
      amountHint: "How much left the shop.",
      category: "Category",
      categoryHint: "Pick a category, or create a new one below.",
      newCategory: "New category",
      newCategoryHint: "Create a reusable category for expenses.",
      categoryCreated: "Expense category added.",
      date: "Date",
      dateHint: "The day the money left. Reports count it on this day.",
      noteHint: "What was it for? Rent, materials, delivery payouts…",
      todayTotal: "Today's spend",
      created: "Expense added.",
      saved: "Expense saved.",
      newTitle: "New Expense",
      editTitle: "Edit Expense",
      notFoundTitle: "Expense not found",
      notFoundBody: "Go back to the list.",
    },
    reports: {
      periodDaily: "Daily",
      periodMonthly: "Monthly",
      periodYearly: "Yearly",
      moneyIn: "Money in",
      refunds: "Refunds",
      itemsCost: "Items cost",
      deliveryIncome: "Delivery income",
      deliveryCost: "Delivery cost",
      expenses: "Spends",
      profit: "Profit",
      loss: "Loss",
      byCategory: "Spends by category",
      noExpenses: "No spends this period.",
      noPayments: "No payments this period.",
      reportPl: "Profit & loss",
      reportChannels: "Sales pages",
      reportStock: "Stock movements",
      chooseReport: "Choose a report to view.",
      availableReports: "Available",
      recommendedReports: "Recommended",
      reportCustomerDebt: "Customer debt",
      totalOwed: "Total owed",
      unpaidOrders: "Unpaid orders",
      oldestOrder: "Oldest order",
      days0To7: "0–7 days",
      days8To30: "8–30 days",
      days31To60: "31–60 days",
      over60Days: "Over 60 days",
      searchCustomerDebt: "Search customer or phone…",
      customerDebtAsOf: "{count} customers owing as of {day}",
      reportProductPerformance: "Product performance",
      unitsSold: "Units sold",
      returnedUnits: "Returns",
      exchangedUnits: "Exchanges",
      landedCost: "Landed cost",
      searchProducts: "Search product, size, color or SKU…",
      productPerformanceTiming: "Units follow stock movement dates. Revenue, landed cost, and profit follow payment dates.",
      reportInventoryValue: "Inventory value",
      currentQty: "Current stock",
      weightedLandedCost: "Average landed cost",
      totalValue: "Total value",
      totalUnits: "Stock units",
      variantCount: "Variants",
      inactiveStockRows: "Inactive variants",
      allInventory: "All inventory",
      searchInventory: "Search product, size, color or SKU…",
      inventoryValueHint: "Value uses positive ledger stock × weighted-average landed cost. Negative stock stays visible but is valued at zero.",
      reportDeadStock: "Dead stock",
      daysWithoutSale: "Days without sale",
      lastSale: "Last sale",
      neverSold: "Never sold",
      tiedUpValue: "Value tied up",
      daysThreshold: "{days}+ days",
      deadStockHint: "Only variants with stock are shown. Never-sold items age from their first stock-in date; sold items age from their latest outbound sale.",
      reportReorder: "Reorder planning",
      reportPurchasesSuppliers: "Purchases & suppliers",
      reportCashPayments: "Cash & payments",
      reportExpenseTrends: "Expense trends",
      reportDeliveryPerformance: "Delivery performance",
      reportStaffPerformance: "Staff performance",
      reportReturnsExchanges: "Returns & exchanges",
      reportCustomerValue: "Customer value",
      customerDebtDescription: "See what each customer owes and how long balances have been outstanding.",
      productPerformanceDescription: "Compare units, revenue, landed cost, profit, returns, and exchanges by product, size, and color.",
      inventoryValueDescription: "See current quantities, weighted-average costs, and the total value held in stock.",
      deadStockDescription: "Find products that remain in stock without selling and see how much cash is tied up.",
      reorderDescription: "Estimate stock remaining and suggested reorder quantities from recent sales.",
      purchasesSuppliersDescription: "Compare supplier spending, purchase costs, delivery costs, and cost changes over time.",
      cashPaymentsDescription: "Review cash, bank transfers, other payments, and refunds for daily closing.",
      expenseTrendsDescription: "Compare expense categories over time and identify unusually high spending.",
      deliveryPerformanceDescription: "Compare delivery success, returns, customer fees, and company costs.",
      staffPerformanceDescription: "Review sales, profit, discounts, cancellations, adjustments, and payments by staff member.",
      returnsExchangesDescription: "Find frequently returned or exchanged products, sizes, and colors.",
      customerValueDescription: "Compare customer orders, revenue, profit, average order value, and outstanding balances.",
      ordersCol: "Orders",
      revenueCol: "Revenue",
      profitCol: "Profit",
      noChannels: "No sales this period.",
      stockFrom: "From",
      stockTo: "To",
      allReasons: "All types",
      itemCol: "Item",
      inOutCol: "In / out",
      byCol: "By",
      noMovements: "No stock movements in this range.",
      exportCsv: "Export CSV",
      csvDay: "Day",
      exportDone: "Report file downloaded.",
      reorderAsOf: "As of {day}",
      lookbackWindow: "Sales window",
      targetCover: "Cover days",
      daysUnit: "{days} days",
      unitsSoldInWindow: "Sold in window",
      avgDailyUnits: "Avg / day",
      daysRemainingCol: "Days left",
      suggestedReorderQty: "Suggested order",
      estimatedReorderCost: "Est. cost",
      reorderTotalsUnits: "Units to order",
      reorderTotalsVariants: "Variants to reorder",
      reorderHint:
        "Suggested quantity = average daily sales (from the sales window) × cover days − current stock. Nothing appears for variants with no recent sales — check Dead stock instead.",
      reorderEmpty: "Nothing to reorder right now.",
    },
    dashboard: {
      todayTitle: "Today",
      // Welcome greeting with the staff member's first name, by time of day.
      greetingMorning: "Good morning, {name}",
      greetingAfternoon: "Good afternoon, {name}",
      greetingEvening: "Good evening, {name}",
      // The range filter chips (Today reuses todayTitle).
      range7d: "7 days",
      range30d: "30 days",
      rangeMtd: "This month",
      rangeYtd: "This year",
      // The five KPI cards.
      kpiSales: "Sales",
      kpiPurchases: "Purchases",
      kpiSalesDue: "Sales due",
      kpiInvoices: "Invoices",
      kpiProfit: "Profit",
      chartSalesPurchases: "Sales & Purchases",
      topProductsTitle: "Top selling products",
      topProductsEmpty: "No sales in this range yet.",
      topCustomersTitle: "Top customers",
      topCustomersEmpty: "No payments in this range yet.",
      other: "Other",
      stockValueTitle: "Stock value",
      stockUnits: "{n} units",
      recentSalesTitle: "Recent sales",
      recentSalesEmpty: "No orders in this range yet.",
      timeJustNow: "Just now",
      timeMinutesAgo: "{n} min ago",
      timeHoursAgo: "{n} h ago",
      timeDaysAgo: "{n} days ago",
      timeDayAgo: "1 day ago",
      lowStockTitle: "Low stock",
      lowStockEmpty: "All stock is fine.",
      quickActions: "Quick actions",
      setupTitle: "Set up your shop first",
      setupBody:
        "Welcome! Add your shop name, currency and timezone in Settings, then the dashboard will come alive.",
      setupCta: "Open Settings",
      qaNewSale: "New Sale",
      qaNewPurchase: "New Purchase",
      qaNewExpense: "New Expense",
      qaDelivery: "Delivery Report",
      qaStock: "Stock",
      qaAdjustment: "Stock Adjustment",
      qaStocktake: "Stocktake",
      viewAllUnpaid: "View all",
      reminder: "Payment reminder",
      reminderMessage:
        "Hello {name}, this is {shop}. Your order {code} still has {amount} left to pay. Thank you!",
      copy: "Copy message",
      copied: "Copied.",
      openWhatsApp: "WhatsApp",
      openTelegram: "Telegram",
    },
    deliveryCompanies: {
      addCompany: "Add Delivery Company",
      searchPlaceholder: "Search by name…",
      nameHint: "e.g. Virak Buntham",
      phone: "Phone",
      phoneHint: "Optional. Companies never log in — this is for calling them.",
      defaultFee: "Default fee (what you pay)",
      defaultFeeHint:
        "Auto-filled per order when this company is picked. Override per order anytime.",
      created: "Delivery company added.",
      saved: "Delivery company saved.",
      newTitle: "New Delivery Company",
      editTitle: "Edit Delivery Company",
      activeHint: "Turn off to hide this company when creating a sale.",
      notFoundTitle: "Delivery company not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
      moduleOffTitle: "Delivery module is off",
      moduleOffBody:
        "Companies are saved but hidden at checkout. Turn it on in Shop Settings.",
    },
    purchases: {
      addPurchase: "New Purchase",
      searchPlaceholder: "Search by code…",
      allStatuses: "All statuses",
      code: "Code",
      createdLabel: "Created",
      supplier: "Supplier",
      items: "Items",
      totalCost: "Total cost",
      newTitle: "New Purchase",
      editTitle: "Edit Purchase",
      supplierHint: "Who sold you this stock.",
      purchasedDate: "Purchase date",
      arrivalDate: "Arrival date",
      arrivalDateHint:
        "Leave empty while the goods are on the way. Enter the arrival date to mark the purchase as arrived — the stock is added on that date.",
      notesHint: "Anything to remember about this purchase.",
      quickAddSupplier: "New supplier",
      quickAddSupplierHint: "Save it and it is picked for this purchase.",
      linesTitle: "Items",
      linesHint: "Pick a product, then set quantities and unit costs for the sizes you need.",
      pickProduct: "Pick a product…",
      pickSize: "Pick a size",
      pickColor: "Pick a color",
      product: "Product",
      size: "Size",
      color: "Color",
      qty: "Qty",
      unitCost: "Supplier unit cost",
      costAfterDelivery: "Cost after delivery",
      applyToAll: "Apply to all sizes",
      addLine: "Add line",
      saveItem: "Save item",
      addItemTitle: "Add item",
      editItemTitle: "Edit item",
      emptyLines: "No items yet — add your first line above.",
      totalPieces: "Total pieces",
      orderSummary: "Order summary",
      itemsCost: "Items cost",
      deliveryCost: "Delivery cost",
      deliveryCostHint: "Added automatically across all purchased pieces when calculating product cost.",
      deliveryPerPiece: "Delivery per piece",
      otherCost: "Other cost",
      grandTotal: "Grand total",
      created: "Purchase created.",
      saved: "Purchase saved.",
      notArrived: "Not yet arrived",
      arrived: "Arrived",
      stockInOn: "Stock in on {value}",
      notFoundTitle: "Purchase not found",
      notFoundBody: "Go back to the list.",
      needLines: "Add at least one item before saving.",
      invalidLines: "Some rows aren't filled in right — check the quantities, costs, and sale prices.",
      needSupplier: "Pick a supplier first.",
      arrivalBeforePurchase: "The arrival date can't be before the purchase date.",
      priceWillChange: "Sale price changes to {value}",
      unarriveTitle: "Remove the arrival date?",
      unarriveBody: "This takes the stock this purchase brought in back off your shelves.",
      stockInTitle: "Stock in from this purchase",
      stockInHint: "Every piece this purchase brought in. Editing a line updates these rows.",
    },
    channels: {
      addChannel: "Add Sales Page",
      searchPlaceholder: "Search by name…",
      nameHint: "e.g. Facebook — Doly Outfits",
      type: "Type",
      typeHint: "Used to group sales in reports.",
      created: "Sales page added.",
      saved: "Sales page saved.",
      newTitle: "New Sales Page",
      editTitle: "Edit Sales Page",
      activeHint: "Turn off to hide this page when creating a sale.",
      notFoundTitle: "Sales page not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
      types: {
        facebook: "Facebook",
        instagram: "Instagram",
        tiktok: "TikTok",
        walk_in: "Walk-in",
        custom: "Other",
      },
    },
    customers: {
      addCustomer: "Add Customer",
      searchPlaceholder: "Search by name or phone…",
      nameHint: "e.g. Sokha Nhem",
      phone: "Phone",
      phoneHint: "Digits only — used to find this customer fast at checkout.",
      address: "Address",
      addressHint: "Where deliveries go. Optional.",
      notes: "Notes",
      notesHint: "Preferred sizes, delivery spots, anything to remember.",
      created: "Customer added.",
      saved: "Customer saved.",
      newTitle: "New Customer",
      editTitle: "Edit Customer",
      activeHint: "Turn off to hide this customer when choosing on a sale.",
      notFoundTitle: "Customer not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
      duplicateTitle: "This customer already exists",
      duplicateBody: "A customer with this phone is already saved. Use that customer instead.",
      useExisting: "Use existing",
      existingSelected: "Existing customer selected.",
      owedTitle: "Still owed",
      owedOrders: "{n} unpaid orders",
      owedEmpty: "No unpaid orders for this customer.",
      owedPaidOf: "Paid {paid} of {total}",
    },
    stock: {
      searchPlaceholder: "Search products…",
      variantSearchPlaceholder: "Search by size, color or SKU…",
      productCol: "Product",
      variantsCol: "Variants",
      availableStock: "Available stock",
      statusCol: "Status",
      lastUpdatedCol: "Last updated",
      lastMovementCol: "Last movement",
      variantCol: "Variant",
      viewVariants: "View variants",
      viewMovements: "View movements",
      statusInStock: "In stock",
      statusLowStock: "Low stock",
      statusOutOfStock: "Out of stock",
      variantsSummary: "{n} variants",
      plusN: "+{n}",
      noColor: "No color",
      needsAttentionOne: "{n} product needs attention",
      needsAttentionMany: "{n} products need attention",
      remaining: "{n} remaining",
      reorderLevel: "Reorder level: {n}",
      createPurchaseOrder: "Create purchase order",
      viewProduct: "View product",
      viewAll: "View all",
      allStatuses: "All",
      sortByQty: "Sort by quantity",
      clearFilters: "Clear filters",
      typeCol: "Type",
      movementCol: "Movement",
      referenceCol: "Reference",
      movementBalanceCol: "Balance",
      referenceOrder: "Order #{code}",
      referencePo: "PO #{code}",
      noMovements: "No stock movements found for this variant.",
      filteredEmpty: "No variants match your filters.",
      adjustStock: "Adjust stock",
      currentStock: "Current stock: {n}",
      sizeCol: "Size",
      colorCol: "Color",
      skuCol: "SKU",
      qtyCol: "In stock",
      exportCsv: "Export CSV",
      exportDone: "Stock file downloaded.",
      lowStockBadgeAria: "{n} low-stock items",
      emptyHistory: "No movements yet.",
      movedBy: "By",
      dateCol: "Date",
      reasonCol: "Reason",
      notFoundTitle: "Product not found",
      notFoundBody: "Go back to the stock list.",
      reasons: {
        purchase: "Purchase",
        sale: "Sale",
        return: "Return",
        exchange_out: "Exchange out",
        exchange_in: "Exchange in",
        cancel: "Cancelled",
        adjustment: "Adjustment",
        stocktake: "Stocktake",
      },
      actions: {
        purchase: "Stock received",
        sale: "Sold through order",
        return: "Returned to stock",
        exchange_out: "Exchanged out",
        exchange_in: "Exchanged in",
        cancel: "Cancelled — returned to stock",
        adjustment: "Manual adjustment",
        stocktake: "Stocktake count",
      },
      openingStock: "Opening stock",
      stockIn: "Stock in",
      stockOut: "Stock out",
      closingStock: "Closing stock",
      allSigns: "All directions",
      allUsers: "All staff",
      balanceCol: "Balance",
      stockCol: "Stock",
      netCol: "Net",
      unitCost: "Unit cost",
      showMovements: "Show {n} movements",
      showMovementsOne: "Show {n} movement",
      hideMovements: "Hide movements",
      openingAtRange: "Opening at {day}",
      stockInDuring: "Stock in during range",
      stockOutDuring: "Stock out during range",
      closingAtRange: "Closing at {day}",
      currentStockBare: "Current stock",
      currentStockToday: "Current stock today: {n}",
      noStockChange: "No stock change",
      movementFlow: "Movement flow",
      movementFlowOrder: "Oldest → newest",
      combined: {
        saleCancel: "Sold and cancelled",
        returnAdjustment: "Returned and damaged",
      },
      operations: {
        purchase: "Stock received",
        sale: "Sale created",
        return: "Items returned",
        exchange_out: "Items exchanged",
        exchange_in: "Items exchanged",
        cancel: "Items cancelled",
        adjustment: "Manual adjustment",
        stocktake: "Stocktake",
      },
      flowDiagnostic:
        "Movement flow diagnostic — this operation's balance chain is incomplete; the ledger itself is verified separately.",
      sortNewestFirst: "Newest first",
      sortOldestFirst: "Oldest first",
      integrityWarning:
        "Stock balance doesn't match — the ledger shows {expected}, this view shows {actual}.",
    },
    adjustments: {
      quickTitle: "Quick stock in / out",
      quickHint: "Add or remove pieces by hand — damaged, found, giveaway…",
      stocktakeTitle: "Full stocktake",
      stocktakeHint:
        "Count what is really on the shelf, then save. Differences are written as stock movements.",
      searchItems: "Search items…",
      pickItem: "Item",
      noItems: "No items found.",
      inStock: "In stock",
      stockIn: "Stock in",
      stockOut: "Stock out",
      qty: "Qty",
      reasonNote: "Reason / note",
      reasonNoteHint: "Why this stock moved — it shows in the history.",
      reasonDamaged: "Damaged",
      reasonFound: "Found",
      reasonGiveaway: "Giveaway",
      saveAdjustment: "Save adjustment",
      adjustmentSaved: "Adjustment saved.",
      pickFirst: "Pick an item first.",
      needNote: "Say why this stock moved.",
      notEnough: "Only {n} in stock.",
      countedCol: "Counted",
      changesCount: "{n} changes",
      saveStocktake: "Save stocktake",
      stocktakeSaved: "{n} corrections written.",
      recentTitle: "Recent adjustments",
      recentEmpty: "No adjustments yet.",
      selectItemHint: "Tap an item, then choose in or out.",
    },
    products: {
      addProduct: "Add Product",
      searchPlaceholder: "Search by name…",
      allCategories: "All categories",
      newTitle: "New Product",
      editTitle: "Edit Product",
      nameHint: "e.g. Polka-dot shirt",
      description: "Description",
      descriptionHint: "Shown on the order screen. Optional.",
      category: "Category",
      categoryHint: "Optional. Used to organize and filter products.",
      code: "Code",
      codeHint: "Your own product code — shown on POS cards next to the SKU. Optional.",
      defaultPrice: "Default sell price",
      defaultPriceHint: "Copied to every size and color. Any variant can override it.",
      defaultCost: "Reference cost",
      defaultCostHint: "What this usually costs you. Prefills the purchase cost.",
      hasColors: "Has colors",
      hasColorsHint: "On = each variant is a size × color. Off = sizes only.",
      sizes: "Sizes",
      sizesHint: "Type a size and press Enter, e.g. S, M, L, XL.",
      colors: "Colors",
      colorsHint: "Type a color and press Enter, e.g. Black, White.",
      addTag: "Add",
      photo: "Product photo",
      photoHint: "Shown in the catalog and on the order screen.",
      uploadPhoto: "Upload photo",
      replacePhoto: "Replace",
      removePhoto: "Remove",
      invalidMoney: "Enter an amount like 12.50",
      invalidImage: "Please choose an image file (max 10 MB).",
      created: "Product added.",
      saved: "Product saved.",
      activeHint: "Turn off to hide this product from new sales.",
      notFoundTitle: "Product not found",
      notFoundBody: "It may have been deactivated. Go back to the list.",
      variantsTitle: "Variants",
      variantsHint:
        "Prices start from the product defaults. Type a new value to override — blank falls back to the default.",
      variantsSyncHint:
        "Changing sizes or colors adds new variants and hides removed ones. Stock history is kept.",
      selectAll: "Select all",
      clearSelection: "Clear",
      selectedCount: "selected",
      applyTo: "Set for selected:",
      applyPrice: "Apply price",
      applyCost: "Apply cost",
      clearOverrides: "Clear overrides",
      applied: "Variants updated.",
      custom: "custom",
      sku: "SKU",
      skuHint: "Optional code per variant.",
      priceCol: "Sell price",
      costCol: "Cost",
    },
    sales: {
      newSale: "New Sale",
      filterHint: "Choose only what you need, then close this panel.",
      searchProducts: "Search products…",
      noProducts: "No products found.",
      noProductsInStock: "No products in stock.",
      allSizes: "All sizes",
      category: "Category",
      allCategories: "All categories",
      clearFilters: "Clear filters",
      pickProductHint: "Pick a size (and color), then Add.",
      size: "Size",
      color: "Color",
      inStock: "in stock",
      outOfStock: "Out of stock",
      addToCart: "Add",
      cart: "Cart",
      cartEmpty: "Cart is empty — add items to start the sale.",
      viewCart: "View cart",
      item: "Product",
      qty: "Qty",
      sku: "SKU",
      code: "Code",
      price: "Price",
      itemDiscount: "Item discount",
      remove: "Remove",
      itemsCount: "items",
      subtotal: "Subtotal",
      customer: "Customer",
      selectCustomer: "Select customer",
      walkInCustomer: "Walk-in Customer",
      customerHint: "Who is buying? Pick an existing customer or create a new one.",
      searchCustomers: "Search by name or phone…",
      newCustomer: "New customer",
      noCustomers: "No customers match.",
      addAddress: "Add address",
      addressSaved: "Address saved.",
      channel: "Sales page",
      channelHint: "Where did this order come from?",
      delivery: "Delivery",
      location: "Address",
      company: "Company",
      noCompany: "Self / pickup",
      companyFee: "Customer fee",
      companyCost: "Company cost",
      companyCostHint: "What YOU pay the company for this order.",
      orderDiscount: "Order discount",
      orderDiscountHint: "Off the whole order. Optional.",
      payment: "Payment",
      method: "Method",
      methods: { cash: "Cash", bank_transfer: "Bank transfer", other: "Other", refund: "Refund" },
      amountReceived: "Amount received",
      paymentDate: "Payment date",
      paymentNote: "Payment note",
      paymentNoteHint: "Saved with the payment — visible in the payment history.",
      saleNote: "Sale note",
      saleNoteHint: "Optional note on the order.",
      notPaid: "Not paid yet",
      remaining: "Remaining",
      changeDue: "Change due",
      total: "Total",
      paid: "Paid",
      unpaid: "Unpaid",
      partial: "Partial",
      completeSale: "Complete sale",
      totalPayable: "Total Payable",
      payNow: "Pay Now",
      home: "Home",
      reset: "Reset",
      refreshProducts: "Refresh products",
      paymentCheckout: "Payment Checkout",
      transactionSummary: "Transaction Summary",
      totalAmount: "Total Amount",
      completePayment: "Complete payment",
      saleDate: "Sale date",
      paymentType: "Payment type",
      paidAmount: "Paid amount",
      customerInfo: "Customer info",
      reviewSale: "Review sale",
      reviewSaleHint: "Check everything before completing the order.",
      confirmCompleteSale: "Confirm & Complete Sale",
      back: "Back",
      tax: "Tax",
      saleCreated: "Sale {code} created.",
      invoice: "Invoice",
      print: "Print",
      printReceipt: "Receipt (thermal)",
      printLabel: "Package label",
      printA5: "A5 invoice",
      receiptSent: "Receipt sent to the printer.",
      labelSent: "Package label sent to the printer.",
      printHint:
        "Set up the 80mm printer in Settings to print receipts and package labels.",
      close: "Close",
      order: "Order",
      date: "Date",
      by: "By",
      signature: "Signature",
      thankyou: "Thank you for supporting us <3",
      deliveryFee: "Shipping fee",
      deliveryFeeHint: "Charged to the customer. Optional.",
      discount: "Discount",
      totalQty: "Total qty",
      profit: "Profit",
      createdBy: "Created by",
      receivePayment: "Receive payment",
      refund: "Refund",
      paymentHistory: "Payment history",
      orderHistory: "Order history",
      events: {
        created: "Order created",
        statusChanged: "Status changed",
        paymentReceived: "Payment received",
        refundGiven: "Refund given",
        linesAdjusted: "Delivery quantities saved",
        itemSwapped: "Item swapped",
        itemAdded: "Item added",
        itemRemoved: "Item removed",
        itemQtyChanged: "Quantity changed",
        itemsReturned: "Item returned",
        deliveryOutcome: "Delivery outcome",
        deliveryCostChanged: "Delivery cost",
        saleEdited: "Order edited",
        saleEditedFields: {
          customer: "Customer",
          channel: "Sales page",
          deliveryCompany: "Company",
          deliveryFee: "Customer fee",
          deliveryCost: "Company cost",
          discount: "Discount",
          note: "Note",
          price: "Price",
          itemDiscount: "Item discount",
        },
      },
      adjustments: "Order adjustments",
      adjust: "Adjust",
      adjustDeliveredTitle: "Adjust delivery",
      adjustDeliveredHint: "How many pieces did the customer actually take? The rest goes back to stock.",
      deliveredQty: "Delivered",
      returnedQty: "Returned",
      allDelivered: "All delivered",
      // Return dialogs bound by what the customer currently holds — "All
      // delivered" would be wrong there (returned pieces were delivered once).
      returnAll: "Return all",
      noneDelivered: "None delivered",
      linesAdjusted: "Delivery quantities saved.",
      itemAdded: "Item added.",
      itemRemoved: "Item removed.",
      itemSwapped: "Item swapped.",
      returnItem: "Return",
      returnItemTitle: "Return item",
      returnItemHint: "Pieces the customer brought back go to stock. Giving money back is a separate refund on this order.",
      returnQty: "Return qty",
      refundAmount: "Refund amount",
      returnRefundHint: "Optional — record the money given back as a refund on this order.",
      itemsReturned: "Item returned.",
      nothingToReturn: "Nothing to return — the customer isn't holding any pieces.",
      // Guided return/correction (Edit Sale + cancel review): the dialog
      // asks what physically happened to pieces the customer was holding.
      resolutionTitle: "What happened to these pieces?",
      resolutionHint:
        "The customer is holding {qty}. Pick what actually happened so stock and the bill stay right.",
      resolutionQty: "Pieces",
      resolutionReason: "Reason",
      resolutionReasonPlaceholder: "What really happened?",
      resolutionReasonRequired: "A reason is required for this correction.",
      resolutionRefund: "Refund",
      resolutionRefundHint: "Optional — money given back is recorded as a refund.",
      resolutionCancel: "Discard",
      resolutionConfirm: "Add to changes",
      outcomeReturnedSellable: "Returning to sellable stock",
      outcomeReturnedSellableHint: "Goods came back and can be sold again.",
      outcomeReturnedDamaged: "Returned damaged",
      outcomeReturnedDamagedHint: "Goods came back but can't be sold — recorded as damaged.",
      outcomeStillWithCustomer: "Still with customer",
      outcomeStillWithCustomerHint: "Nothing was returned — the pieces stay on the bill.",
      outcomeDeliveryIncorrect: "Delivery was wrong — never handed over",
      outcomeDeliveryIncorrectHint:
        "The order says delivered but the goods never left the shop. Owner-only, with a reason.",
      cancelReviewTitle: "Cancel this order?",
      cancelReviewHint:
        "Every piece the customer is holding needs a physical outcome before this order can be cancelled.",
      cancelReviewStillHeld:
        "{qty} pieces still with the customer — pick what happened to them.",
      cancelReviewResolveAll: "Mark all as returned",
      cancelReviewResolveAllDamaged: "Mark all as damaged",
      cancelReviewReason: "Cancellation reason",
      cancelReviewReasonPlaceholder: "Why is this order being cancelled?",
      cancelled: "Order cancelled.",
      orderDetails: "Order details",
      expectedProfit: "Expected order profit",
      groupLines: "{n} sale lines",
      groupShowDetails: "Show details",
      groupHideDetails: "Hide details",
      groupMultiplePrices: "Multiple prices",
      groupIntegrity: "Check the data — these quantities don't add up.",
      paymentSummaryTotal: "Order total",
      paymentSummaryNetPaid: "Net paid",
      paidInFull: "Paid in full",
      refundDue: "Refund due",
      receivedRefunded: "Received {received} · Refunded {refunded}",
      refundConfirmTitle: "Refund {amount} to the customer?",
      refundConfirmNetAfter: "Net paid after refund: {amount}",
      refundConfirmRemainingAfter: "Remaining after refund: {amount}",
      noPaymentsYet: "No payments recorded yet",
      paymentReceived: "Payment received",
      refundIssued: "Refund issued",
      stateAwaiting: "{qty} awaiting",
      stateWithCustomer: "{qty} with customer",
      stateCancelled: "{qty} cancelled",
      stateReturned: "{qty} returned",
      lineStateReturnedSellable: "Returned · Sellable",
      markPending: "Mark pending",
      markPacked: "Mark packed",
      markDelivering: "Mark delivering",
      markDelivered: "Mark delivered",
      markPartiallyDelivered: "Mark partially delivered",
      cancelOrder: "Cancel order",
      cancelConfirmTitle: "Cancel this order?",
      cancelConfirmBody: "Unsold pieces go back to stock. This can't be undone.",
      keepShippingFee: "Customer still pays shipping",
      keepShippingFeeHint:
        "Tick this when the package already went out and the customer refused it — the shipping fee stays owed on the cancelled order.",
      refundHint: "Money given back to the customer is recorded here as a refund.",
      paymentAdded: "Payment received.",
      refundAdded: "Refund recorded.",
      statusUpdated: "Order status updated.",
      allStatuses: "All statuses",
      today: "Today",
      allChannels: "All pages",
      searchCode: "Search invoice, e.g. 001…",
      view: "View",
      due: "Due",
      fromDate: "From",
      toDate: "To",
      allPaymentStatuses: "All payment statuses",
      editSale: "Edit sale",
      updateStatus: "Update status",
      status: "Status",
      currentStatus: "Current status",
      noStatusSteps: "No status changes available.",
      statusNow: "Now",
      statusPickHint: "Pick where this order is now. Greyed steps can't be used from here.",
      partiallyDeliveredHint:
        "The customer kept only some pieces at the door — the rest goes back to stock.",
      saleDetail: "Sale detail",
      saleReturn: "Sale return",
      showPayments: "Show payment",
      createPayment: "Create a payment",
      cancelSale: "Cancel sale",
      paymentStatus: "Payment status",
      paymentStatuses: {
        paid: "Paid",
        partlyPaid: "Partly paid",
        unpaid: "Unpaid",
      },
      saleEdited: "Sale updated.",
      paymentAddedWithChange: "Payment received. Change due: {amount}.",
      cancelPaidHint:
        "This order has {amount} paid — give the money back with a refund after cancelling.",
      notFoundTitle: "Order not found",
      notFoundBody: "This order doesn't exist or may have been removed.",
      itemQtys: {
        ordered: "Ordered",
        delivered: "Delivered",
        cancelled: "Cancelled",
        returned: "Returned",
        withCustomer: "Customer has",
        notDeliveredYet: "Awaiting delivery",
        saleLineSku: "Sale line / SKU",
      },
      emptyHistory: "Nothing here yet.",
      // The full-page order editor. Nothing here touches stock until Save —
      // the wording says so, because that is the whole point of the page.
      edit: {
        title: "Edit Sale",
        breadcrumb: "Sales",
        breadcrumbEdit: "Edit",
        orderCard: "Order information",
        orderCardHint: "Who this order is for and where it came from.",
        itemsCard: "Items",
        itemsCardHint:
          "Change quantities, prices or discounts. Stock moves only when you save.",
        summaryCard: "Order summary",
        addItem: "Add an item",
        addItemPlaceholder: "Search by product name or SKU…",
        noMatches: "No items match.",
        colItem: "Item",
        colVariant: "Variant / SKU",
        colPrice: "Unit price",
        colStock: "Available stock",
        colQty: "Quantity",
        colDiscount: "Discount",
        colSubtotal: "Subtotal",
        colAction: "Action",
        emptyItems: "No items on this order yet — search above to add one.",
        notEnoughStock: "Only {qty} available.",
        // A raise is measured as a DELTA against the line's billed quantity:
        // the shelf funds extra pieces, and the message says exactly how many
        // and the ceiling it may reach — never a raw stock comparison.
        raiseLimit: "Only {qty} more available — maximum total quantity is {max}.",
        // A raise's extra pieces are a new purchase at today's price — shown
        // whenever that differs from the line's own price (the subtotal
        // already prices them that way).
        deltaPriceHint: "Extra pieces are priced at today's price.",
        invalidQty: "Enter a whole number, 1 or more.",
        // The edit floor is what the customer HOLDS (invariant 6), not the
        // historical delivered count — returned pieces can drop off the bill.
        belowHeld: "Customer is holding {qty} — use Return instead.",
        discountTooBig: "More than this line is worth.",
        priceRequired: "Enter a price.",
        removeTitle: "Remove this item?",
        removeBody:
          "Its pieces go back to stock when you save. The line stays in the order history.",
        removed: "Removed",
        // A line that bills nothing because its pieces came back. The ledger
        // tells which: sellable returns are a lone return row, damaged ones
        // are netted by an adjustment.
        returnedSellable: "Returned · Sellable",
        returnedDamaged: "Returned · Damaged",
        // A return the staff decided in this window but did NOT save yet —
        // only this state is undoable (a saved return is history).
        pendingReturnSellable: "Pending return · Sellable",
        pendingReturnDamaged: "Pending return · Damaged",
        // A saved return is immutable history — the badge says why there is
        // no Undo beside it.
        historicalReturn: "Historical return · Already saved",
        // What a pending sellable return does to the shelf when saved.
        pendingReturnStockIn: "Stock +{qty} when saved",
        undo: "Undo",
        heldLocked: "{qty} with customer",
        newLine: "New",
        // Extra items added to a DELIVERED order: how the customer gets them,
        // and what that does to the order status.
        fulfillmentAsk: "How will the customer receive the new items?",
        fulfillmentHandedNow: "Handed to customer now",
        fulfillmentDeliverLater: "Deliver later",
        fulfillmentHandedNowHint: "The order stays Delivered.",
        fulfillmentDeliverLaterHint: "The order becomes Partially delivered.",
        statusFollowsFulfillment: "Status follows how the new items are received.",
        // Pending return/correction resolutions shown before Save — the
        // change summary mirrors exactly what the server will apply.
        changeSummaryTitle: "Changes in this save",
        changeSummaryNewItems: "Leaving stock",
        changeSummaryNetStock: "Net stock",
        changeSummaryMoney: "Money",
        changeSummaryPrevTotal: "Previous total",
        changeSummaryNewTotal: "New total",
        changeSummaryAdditional: "Additional owed",
        changeSummaryRefundDue: "Refund due",
        changeSummaryLessOwed: "Less owed",
        changeSummaryShippingChange: "Shipping fee change",
        changeSummaryShippingUnchanged: "Shipping fee unchanged",
        changeSummaryEmpty: "No returns or corrections yet.",
        changeSummarySellable: "Returning to sellable stock",
        changeSummaryDamaged: "Returned damaged",
        changeSummaryStill: "Still with customer",
        changeSummaryStillSuffix: "— remains on bill",
        changeSummaryIncorrect: "Delivery was wrong",
        changeSummaryRefund: "Refund",
        changeSummaryUndo: "Undo",
        resolveLine: "Resolve",
        cancelOrderAction: "Cancel order",
        itemsSubtotal: "Items subtotal",
        stillOwed: "Still owed",
        saveChanges: "Save changes",
        saving: "Saving…",
        saved: "Order updated.",
        fixErrors: "Fix the highlighted rows before saving.",
        noChanges: "Nothing has changed yet.",
        unsavedTitle: "Leave without saving?",
        unsavedBody: "Your changes to this order haven't been saved.",
        unsavedLeave: "Leave",
        unsavedStay: "Keep editing",
      },
    },
    // T17 — the evening delivery screen. Plain shop language throughout.
    deliveryReport: {
      title: "Delivery Report",
      hint: "Tonight's packages, grouped by delivery company. Mark each order's outcome from whatever confirmation you got — a photo, a call, or a paper list.",
      openOrders: "Out for delivery",
      markedToday: "Marked today",
      markOutcome: "Mark delivery outcome",
      outcome: {
        delivered: "Delivered",
        partial: "Partial",
        returned: "Returned",
        cancelled: "Cancelled",
      },
      summary: {
        handled: "Handled",
        delivered: "Delivered",
        partial: "Partial",
        returns: "Returns",
        cancellations: "Cancellations",
        feePayable: "Fee payable",
      },
      packagingPhoto: "Packaging photo",
      uploadPhoto: "Upload photo",
      photoUploaded: "Photo saved.",
      deliveryOff:
        "Delivery is off. Turn on the delivery module in Shop Settings to use this screen.",
      noOrders: "Nothing to mark tonight — no orders are out for delivery.",
      partialTitle: "Mark partially delivered",
      partialHint:
        "How many of each item did the customer take? The rest goes back to stock.",
      mark: "Mark outcome",
      outcomeMarked: "Outcome marked.",
      feeUpdated: "Delivery cost updated.",
      selfDelivery: "Self delivery",
      returnedConfirmTitle: "Whole package returned?",
      returnedConfirmBody: "Everything goes back to stock. The order is cancelled.",
      cancelledConfirmTitle: "Cancel this delivery?",
      cancelledConfirmBody: "Everything goes back to stock. The order is cancelled.",
    },
  },
  km: {
    appName: "POS",
    nav: {
      dashboard: "ទំព័រដើម",
      sales: "ការលក់",
      products: "ទំនិញ",
      categories: "ប្រភេទទំនិញ",
      customers: "អតិថិជន",
      stock: "ស្តុក",
      adjustments: "កែតម្រូវស្តុក",
      purchases: "ការទិញចូល",
      suppliers: "អ្នកផ្គត់ផ្គង់",
      delivery: "ក្រុមហ៊ុនដឹកជញ្ជូន",
      deliveryReport: "របាយការណ៍ដឹកជញ្ជូន",
      channels: "ទំព័រលក់",
      expenses: "ចំណាយ",
      reports: "របាយការណ៍",
      settings: "ការកំណត់ហាង",
      more: "ច្រើនទៀត",
    },
    common: {
      save: "រក្សាទុក",
      cancel: "បោះបង់",
      add: "បន្ថែម",
      edit: "កែប្រែ",
      delete: "លុប",
      search: "ស្វែងរក",
      actions: "សកម្មភាព",
      active: "ដំណើរការ",
      inactive: "ផ្អាក",
      confirm: "យល់ព្រម",
      back: "ត្រឡប់ក្រោយ",
      total: "សរុប",
      note: "កំណត់ចំណាំ",
      name: "ឈ្មោះ",
      phone: "លេខទូរស័ព្ទ",
      address: "អាសយដ្ឋាន",
      date: "កាលបរិច្ឆេទ",
      email: "អ៊ីមែល",
      role: "តួនាទី",
      yes: "បាទ/ចាស",
      no: "ទេ",
      close: "បិទ",
      filter: "តម្រង",
      rowsPerPage: "ចំនួនក្នុងមួយទំព័រ",
      page: "ទំព័រ",
      of: "នៃ",
      noResults: "រកមិនឃើញទិន្នន័យ",
      loading: "កំពុងផ្ទុក…",
      optional: "ស្រេចចិត្ត",
      required: "តម្រូវ",
      roleOwner: "ម្ចាស់ហាង",
      roleStaff: "បុគ្គលិក",
      signOut: "ចាកចេញ",
      columns: "ជួរឈរ",
      showAll: "បង្ហាញទាំងអស់",
      comingSoon: "នឹងមានឆាប់ៗនេះ",
      useTyped: 'ប្រើ "{value}"',
      more: "បង្ហាញបន្ថែម",
      lightMode: "របៀបពន្លឺ",
      darkMode: "របៀបងងឹត",
      // Global AppHeader controls
      pos: "POS",
      profile: "ប្រវត្តិរូប",
      appearance: "រូបរាង",
      themeSystem: "តាមប្រព័ន្ធ",
      enterFullscreen: "បើកពេញអេក្រង់",
      exitFullscreen: "ចេញពីពេញអេក្រង់",
      language: "ភាសា",
      languageEnglish: "អង់គ្លេស",
      languageKhmer: "ភាសាខ្មែរ",
      expandSidebar: "បើករបារចំហៀង",
      collapseSidebar: "បិទរបារចំហៀង",
    },
    status: {
      draft: "ព្រាង",
      confirmed: "បានបញ្ជាក់",
      pending: "កំពុងរង់ចាំ",
      packed: "បានខ្ចប់",
      delivering: "កំពុងដឹកជញ្ជូន",
      delivered: "បានទទួល",
      partially_delivered: "ទទួលបានមួយផ្នែក",
      cancelled: "បានបោះបង់",
      received: "បានទទួលទំនិញ",
    },
    errors: {
      UNAUTHORIZED: "សូមចូលគណនីម្តងទៀត។",
      FORBIDDEN: "មានតែម្ចាស់ហាងទេដែលអាចធ្វើបាន។",
      NO_SHOP: "សូមបំពេញការកំណត់ហាងជាមុនសិន។",
      NO_STAFF_RECORD: "គណនីនេះមិនទាន់បានភ្ជាប់ទៅហាងនេះទេ។",
      INVALID_MONEY: "សូមបញ្ចូលចំនួនទឹកប្រាក់ត្រឹមត្រូវ។",
      INVALID_QTY: "សូមបញ្ចូលចំនួនត្រឹមត្រូវ។",
      INVALID_DELTA: "សូមបញ្ចូលចំនួនត្រឹមត្រូវ។",
      INVALID_INPUT: "សូមពិនិត្យមើលវាលដែលបានគូសបញ្ជាក់។",
      CANNOT_CHANGE_OWN_ROLE: "មិនអាចប្តូរតួនាទីខ្លួនឯងទេ។",
      CANNOT_DEACTIVATE_SELF: "មិនអាចផ្អាកគណនីខ្លួនឯងទេ។",
      CANNOT_RESET_OWN_PASSWORD: "សូមប្រើការកំណត់ពាក្យសម្ងាត់សម្រាប់គណនីខ្លួនឯង។",
      NOT_FOUND: "រកមិនឃើញទិន្នន័យ។",
      DUPLICATE_CUSTOMER: "មានអតិថិជនដែលប្រើលេខទូរស័ព្ទនេះរួចហើយ។",
      DUPLICATE_EMAIL: "អ៊ីមែលនេះមានគណនីរួចហើយ។",
      OUT_OF_STOCK: "មិនមានស្តុកគ្រប់គ្រាន់សម្រាប់ទំនិញនេះ។",
      EMPTY_CART: "កន្ត្រកទទេ — សូមបន្ថែមទំនិញយ៉ាងហោចមួយ។",
      INVALID_PAYMENT: "ការបង់ប្រាក់ត្រូវតែចន្លោះពី 0 ទៅសរុបនៃការបញ្ជាទិញ។",
      IDEMPOTENCY_CONFLICT: "សំណើរក្សាទុកនេះត្រូវបានផ្ញើរួចជាមួយព័ត៌មានផ្សេង។ សូមពិនិត្យ ហើយផ្ញើម្តងទៀត។",
      INVALID_IDEMPOTENCY_KEY: "មិនអាចកំណត់អត្តសញ្ញាណសំណើរក្សាទុកនេះបានទេ។ សូមផ្ទុកឡើងវិញ ហើយព្យាយាមម្តងទៀត។",
      STALE_EDIT: "ការបញ្ជាទិញនេះបានផ្លាស់ប្តូរនៅក្នុងវិនដូផ្សេង។ សូមផ្ទុកឡើងវិញ រួចព្យាយាមម្តងទៀត។",
      RETURN_EXCEEDS_HELD: "មិនអាចបង្វិលច្រើនជាងអ្វីដែលអតិថិជនកំពុងកាន់បានទេ។",
      DELIVERED_BELOW_RETURNED: "មិនអាចសម្គាល់ចំនួនដឹកជូនតិចជាងចំនួនដែលបានបង្វិលបានទេ។",
      DELIVERED_LOCKED_LINES: "ការបញ្ជាទិញនេះបានដឹកជូនរួចហើយ — ការផ្លាស់ប្តូរទំនិញត្រូវធ្វើតាមលំហូរបង្វិល និងផ្លាស់ប្តូរទំនិញ។",
      CANNOT_CANCEL_HELD: "ទំនិញមួយចំនួននៅជាមួយអតិថិជន — សូមបង្វិល ឬកែតម្រូវទំនិញទាំងនោះ មុនពេលលុបចោលការបញ្ជាទិញ។",
      GENERIC: "មានបញ្ហាបានកើតឡើង។ សូមព្យាយាមម្តងទៀត។",
      // T25 printing
      PRINT_NO_PRINTER: "មិនទាន់បានកំណត់ម៉ាស៊ីនពុម្ពទេ។ សូមបើកការកំណត់ ហើយកំណត់ម៉ាស៊ីនពុម្ពជាមុនសិន។",
      PRINT_FAILED: "បោះពុម្ពមិនបាន — សូមពិនិត្យម៉ាស៊ីនពុម្ព ហើយព្យាយាមម្តងទៀត។",
      PRINT_USB_UNSUPPORTED: "ការពុម្ពតាម USB ត្រូវការ Chrome ឬ Edge លើការតភ្ជាប់ដែលមានសុវត្ថិភាព។",
      PRINT_NO_USB_DEVICE: "រកមិនឃើញម៉ាស៊ីនពុម្ព USB ទេ។ សូមដោតខ្សែ រួចជ្រើសរើសវាម្តងទៀតក្នុងការកំណត់។",
      PRINT_USB_DENIED: "មិនត្រូវបានអនុញ្ញាតឲ្យប្រើ USB ទេ។ សូមអនុញ្ញាតពេលកម្មវិធីរុករកសួរ។",
      PRINT_USB_BUSY:
        "Windows មិនបានផ្តល់ម៉ាស៊ីនពុម្ពនេះឲ្យកម្មវិធីរុករកទេ (ដ្រាយវ័រផ្សេងកំពុងប្រើវា)។ សូមផ្តាច់ខ្សែរួចដោតម្តងទៀត ឬប្រើ QZ Tray / Network ក្នុងការកំណត់។",
      PRINT_QZ_OFFLINE: "QZ Tray មិនបានបើកទេ។ សូមបើក QZ Tray នៅលើកុំព្យូទ័រនេះ រួចព្យាយាមម្តងទៀត។",
      PRINT_QZ_CONFIG: "ការកំណត់ QZ Tray មិនទាន់ពេញលេញ។ សូមពិនិត្យឈ្មោះម៉ាស៊ីនពុម្ព និងវិញ្ញាបនបត្រក្នុងការកំណត់។",
    },
    settings: {
      shopTitle: "ព័ត៌មានហាង",
      shopHint: "ឈ្មោះ លុយ និងពេលវេលា — របាយការណ៍ទាំងអស់ប្រើការកំណត់នេះ។",
      shopName: "ឈ្មោះហាង",
      currency: "រូបិយប័ណ្ណ",
      currencyHint: "កូដ ៣ អក្សរ ឧ. USD ឬ KHR។",
      timezone: "តំបន់ពេលវេលា",
      timezoneSearch: "វាយដើម្បីស្វែងរក…",
      language: "ភាសា",
      languageHint: "ភាសាក្នុងកម្មវិធី។",
      deliveryEnabled: "ក្រុមហ៊ុនដឹកជញ្ជូន",
      deliveryHint:
        "បើក = ការដឹកជញ្ជូនជាមួយក្រុមហ៊ុន។ បិទ = ទទួលនៅហាង ឬដឹកខ្លួនឯង។",
      address: "អាសយដ្ឋាន",
      addressHint: "បង្ហាញលើវិក្កយបត្រដែលបោះពុម្ព។",
      exchangeRate: "អត្រាប្តូរប្រាក់",
      exchangeRateHint: "លុយក្នុងស្រុកក្នុង ១ ឯកតារបស់រូបិយប័ណ្ណអ្នក។ ១ = មិនប្តូរ។",
      lowStockThreshold: "ការព្រមានស្តុកតិច",
      lowStockThresholdHint: "ព្រមានពេលស្តុកតិចជាង ឬស្មើចំនួននេះ។",
      defaultCustomer: "អតិថិជនលំនាំដើម",
      defaultCustomerHint:
        "ជ្រើសរើសដោយស្វ័យប្រវត្តិពេលបើកទំព័រលក់។ ទុកទទេដើម្បីប្រើអតិថិជនចូលហាង។",
      saved: "បានរក្សាទុកការកំណត់។",
      usersTitle: "ក្រុមការងារ",
      usersHint: "អ្នកទាំងអស់ដែលអាចចូលប្រើហាងនេះ។",
      userActive: "កំពុងដំណើរការ",
      userInactive: "បានផ្អាក",
      resetPassword: "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
      resetPasswordHint:
        "កំណត់ពាក្យសម្ងាត់ថ្មីសម្រាប់និទ្ទេសិកានេះ — គេនឹងប្រើវាពេលចូលលើកបន្ទាប់។",
      newPassword: "ពាក្យសម្ងាត់ថ្មី",
      confirmPassword: "បញ្ជាក់ពាក្យសម្ងាត់ថ្មី",
      resetPasswordDone: "ពាក្យសម្ងាត់ត្រូវបានធ្វើបច្ចុប្បន្នភាព។",
      addStaff: "បន្ថែមនិទ្ទេសិកា",
      addStaffHint:
        "បង្កើតគណនីចូលនៅទីនេះ — ផ្តល់អ៊ីមែល និងពាក្យសម្ងាត់ដំបូងឲ្យគេ។ គេអាចផ្លាស់ប្តូរវាបានពេលក្រោយ។",
      staffName: "ឈ្មោះពេញ",
      staffEmail: "អ៊ីមែល",
      startPassword: "ពាក្យសម្ងាត់ដំបូង",
      staffCreated: "{name} ត្រូវបានបន្ថែម — ឥឡូវគេអាចចូលប្រើបានហើយ។",
      deactivateTitle: "ផ្អាកគណនីនិទ្ទេសិកានេះ?",
      deactivateBody:
        "គេនឹងបាត់បង់សិទ្ធិចូលប្រើហាងភ្លាមៗ។ ការលក់ និងចលនាស្តុកចាស់នៅដូចដើម ហើយអ្នកអាចបើកឡើងវិញបានគ្រប់ពេល។",
      deactivateConfirm: "ផ្អាក",
      activateConfirm: "បើកឡើងវិញ",
      changeRole: "តួនាទី",
      ownRoleHint: "មិនអាចប្តូរតួនាទីខ្លួនឯងទេ។",
      notOwnerTitle: "មានតែម្ចាស់ហាងទេដែលអាចបើកការកំណត់",
      notOwnerBody: "សូមចូលជាមួយគណនីម្ចាស់ហាងដើម្បីផ្លាស់ប្តូរការកំណត់។",
      backupTitle: "ច្បាប់ចម្លងទិន្នន័យ",
      backupHint:
        "ទាញយកគ្រប់តារាងក្នុងហាងនេះជាឯកសារ JSON តែមួយ។ រក្សាទុកនៅកន្លែងមានសុវត្ថិភាព — វាជាច្បាប់ចម្លងកំណត់ត្រាអាជីវកម្មរបស់អ្នក។",
      backupAction: "ទាញយកច្បាប់ចម្លង",
      backupDone: "ទាញយករួច — {n} តារាង។",
      // T25 printing
      printerTitle: "ម៉ាស៊ីនពុម្ពវិក្កយបត្រ",
      printerHint:
        "ម៉ាស៊ីនពុម្ពកម្ដៅទំហំ 80មម សម្រាប់វិក្កយបត្រ និងស្លាកកញ្ចប់។ វិក្កយបត្រ A5 បោះពុម្ពតាមប្រអប់ពុម្ពរបស់កម្មវិធីរុករក ដែលអាចជ្រើសរើសម៉ាស៊ីនពុម្ពណាមួយបាន។",
      printerType: "ការភ្ជាប់",
      printerNone: "គ្មានម៉ាស៊ីនពុម្ពកម្ដៅ",
      printerWebUsb: "ម៉ាស៊ីនពុម្ព USB (WebUSB)",
      printerQzTray: "QZ Tray (USB / បណ្តាញ / ឥតខ្សែ)",
      printerNetwork: "ម៉ាស៊ីនពុម្ពបណ្តាញ (IP)",
      printerTypeHint: "របៀបដែលកម្មវិធីភ្ជាប់ទៅម៉ាស៊ីនពុម្ព 80មម។",
      printerVendorId: "Vendor ID (hex)",
      printerProductId: "Product ID (hex)",
      printerIdsHint: "ប៊ូតុងស្កេនបំពេញដោយស្វ័យប្រវត្តិ — ជាធម្មតាមិនចាំបាច់វាយទេ។",
      printerScan: "ស្កេនម៉ាស៊ីនពុម្ព USB",
      printerScanHint: "ដោតម៉ាស៊ីនពុម្ព ចុចស្កេន រួចជ្រើសរើសវាពីបញ្ជីដែលកម្មវិធីរុករកបង្ហាញ។",
      printerScanDone: "បានភ្ជាប់ម៉ាស៊ីនពុម្ព USB — ចុចរក្សាទុកដើម្បីរក្សាវា។",
      printerQzName: "ឈ្មោះម៉ាស៊ីនពុម្ព",
      printerQzNameHint: "ឈ្មោះម៉ាស៊ីនពុម្ពដូចដែល QZ Tray បង្ហាញ។",
      printerQzCert: "វិញ្ញាបនបត្រ QZ",
      printerQzCertHint:
        "ក្នុង QZ Tray: Advanced → Site Manager → បង្កើតវិញ្ញាបនបត្រ រួចបិទភ្ជាប់ខ្លឹមសារនៃ digital-certificate.txt នៅទីនេះ។",
      printerNetworkHost: "អាសយដ្ឋាន IP របស់ម៉ាស៊ីនពុម្ព",
      printerNetworkHostHint:
        "ត្រូវតែស្ថិតក្នុងបណ្តាញក្នុងស្រុកតែមួយជាមួយម៉ាស៊ីនមេរបស់កម្មវិធី (កុំព្យូទ័រដែលបើកកម្មវិធី)។",
      printerNetworkPort: "ច្រក (Port)",
      printerNetworkPortHint: "ជាធម្មតា 9100។",
      printerTest: "សាកល្បងពុម្ព",
      printerTestDone: "បានផ្ញើទៅម៉ាស៊ីនពុម្ព — សូមពិនិត្យក្រដាស។",
      printerPaperHint:
        "ក្រដាសកម្ដៅពុម្ពអក្សរអង់គ្លេសតែប៉ុណ្ណោះ — ម៉ាស៊ីនពុម្ពនេះមិនគាំទ្រអក្សរខ្មែរទេ។",
      printTestOk: "Printer test - OK",
    },
    categories: {
      addCategory: "បន្ថែមប្រភេទ",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…",
      nameHint: "ឧ. អាវ រ៉ូប ខោខូវប៊យ",
      created: "បានបន្ថែមប្រភេទ។",
      saved: "បានរក្សាទុកប្រភេទ។",
      newTitle: "ប្រភេទថ្មី",
      editTitle: "កែប្រែប្រភេទ",
      activeHint: "បិទដើម្បីលាក់ប្រភេទនេះពេលបន្ថែមទំនិញ។",
      notFoundTitle: "រកមិនឃើញប្រភេទ",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
    },
    suppliers: {
      addSupplier: "បន្ថែមអ្នកផ្គត់ផ្គង់",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…",
      nameHint: "ឧ. Phnom Penh Garment",
      phone: "ទូរស័ព្ទ",
      phoneHint: "ស្រេចចិត្ត។ ប្រើពេលទូរស័ព្ទទាក់ទង។",
      notes: "កំណត់ចំណាំ",
      notesHint: "លក្ខខណ្ឌបង់ប្រាក់ ថ្ងៃដឹកជញ្ជូន អ្វីដែលចង់ចាំ។",
      created: "បានបន្ថែមអ្នកផ្គត់ផ្គង់។",
      saved: "បានរក្សាទុកអ្នកផ្គត់ផ្គង់។",
      newTitle: "អ្នកផ្គត់ផ្គង់ថ្មី",
      editTitle: "កែប្រែអ្នកផ្គត់ផ្គង់",
      activeHint: "បិទដើម្បីលាក់អ្នកផ្គត់ផ្គង់នេះពេលបង្កើតការទិញចូល។",
      notFoundTitle: "រកមិនឃើញអ្នកផ្គត់ផ្គង់",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
    },
    expenses: {
      addExpense: "បន្ថែមការចំណាយ",
      searchPlaceholder: "ស្វែងរកតាមប្រភេទ…",
      amount: "ចំនួនទឹកប្រាក់",
      amountHint: "លុយដែលចេញពីហាង។",
      category: "ប្រភេទ",
      categoryHint: "ជ្រើសរើសប្រភេទ ឬបង្កើតប្រភេទថ្មីខាងក្រោម។",
      newCategory: "ប្រភេទថ្មី",
      newCategoryHint: "បង្កើតប្រភេទដែលអាចប្រើឡើងវិញសម្រាប់ការចំណាយ។",
      categoryCreated: "បានបន្ថែមប្រភេទចំណាយ។",
      date: "កាលបរិច្ឆេទ",
      dateHint: "ថ្ងៃដែលលុយចេញ។ របាយការណ៍រាប់វានៅថ្ងៃនេះ។",
      noteHint: "ចំណាយលើអ្វី? ថ្លៃជួល សម្ភារៈ ថ្លៃដឹកជញ្ជូន…",
      todayTotal: "ចំណាយថ្ងៃនេះ",
      created: "បានបន្ថែមការចំណាយ។",
      saved: "បានរក្សាទុកការចំណាយ។",
      newTitle: "ការចំណាយថ្មី",
      editTitle: "កែប្រែការចំណាយ",
      notFoundTitle: "រកមិនឃើញការចំណាយ",
      notFoundBody: "សូមត្រឡប់ទៅបញ្ជីវិញ។",
    },
    reports: {
      periodDaily: "ប្រចាំថ្ងៃ",
      periodMonthly: "ប្រចាំខែ",
      periodYearly: "ប្រចាំឆ្នាំ",
      moneyIn: "លុយចូល",
      refunds: "ប្រាក់បង្វិល",
      itemsCost: "ថ្លៃទំនិញ",
      deliveryIncome: "ចំណូលដឹកជញ្ជូន",
      deliveryCost: "ថ្លៃដឹកជញ្ជូន",
      expenses: "ការចំណាយ",
      profit: "ចំណេញ",
      loss: "ខាត",
      byCategory: "ការចំណាយតាមប្រភេទ",
      noExpenses: "គ្មានការចំណាយក្នុងរយៈពេលនេះ។",
      noPayments: "គ្មានការបង់ប្រាក់ក្នុងរយៈពេលនេះ។",
      reportPl: "ចំណេញនិងខាត",
      reportChannels: "ទំព័រលក់",
      reportStock: "ចលនាស្តុក",
      chooseReport: "ជ្រើសរើសរបាយការណ៍ដើម្បីមើល។",
      availableReports: "អាចប្រើបាន",
      recommendedReports: "បានណែនាំ",
      reportCustomerDebt: "បំណុលអតិថិជន",
      totalOwed: "សរុបជំពាក់",
      unpaidOrders: "ការបញ្ជាទិញមិនទាន់បង់",
      oldestOrder: "ការបញ្ជាទិញចាស់បំផុត",
      days0To7: "០–៧ ថ្ងៃ",
      days8To30: "៨–៣០ ថ្ងៃ",
      days31To60: "៣១–៦០ ថ្ងៃ",
      over60Days: "លើស ៦០ ថ្ងៃ",
      searchCustomerDebt: "ស្វែងរកអតិថិជន ឬលេខទូរស័ព្ទ…",
      customerDebtAsOf: "អតិថិជន {count} នាក់ជំពាក់ គិតត្រឹម {day}",
      reportProductPerformance: "លទ្ធផលទំនិញ",
      unitsSold: "ចំនួនលក់",
      returnedUnits: "ការបង្វិល",
      exchangedUnits: "ការប្តូរ",
      landedCost: "ថ្លៃដើមក្រោយដឹកជញ្ជូន",
      searchProducts: "ស្វែងរកទំនិញ ទំហំ ពណ៌ ឬ SKU…",
      productPerformanceTiming: "ចំនួនទំនិញគិតតាមថ្ងៃចលនាស្តុក។ ចំណូល ថ្លៃដើម និងចំណេញគិតតាមថ្ងៃទទួលប្រាក់។",
      reportInventoryValue: "តម្លៃស្តុក",
      currentQty: "ស្តុកបច្ចុប្បន្ន",
      weightedLandedCost: "ថ្លៃដើមមធ្យមក្រោយដឹក",
      totalValue: "តម្លៃសរុប",
      totalUnits: "ចំនួនក្នុងស្តុក",
      variantCount: "ទំហំ និងពណ៌",
      inactiveStockRows: "ទំនិញដែលបានបិទ",
      allInventory: "ស្តុកទាំងអស់",
      searchInventory: "ស្វែងរកទំនិញ ទំហំ ពណ៌ ឬ SKU…",
      inventoryValueHint: "តម្លៃគិតពីស្តុកវិជ្ជមានក្នុងប្រវត្តិស្តុក × ថ្លៃដើមមធ្យមក្រោយដឹក។ ស្តុកអវិជ្ជមាននៅតែបង្ហាញ ប៉ុន្តែគិតតម្លៃសូន្យ។",
      reportDeadStock: "ស្តុកមិនដើរ",
      daysWithoutSale: "ថ្ងៃមិនមានការលក់",
      lastSale: "ការលក់ចុងក្រោយ",
      neverSold: "មិនធ្លាប់លក់",
      tiedUpValue: "តម្លៃជាប់ក្នុងស្តុក",
      daysThreshold: "{days}+ ថ្ងៃ",
      deadStockHint: "បង្ហាញតែទំនិញដែលមានស្តុក។ ទំនិញមិនធ្លាប់លក់គិតចាប់ពីថ្ងៃស្តុកចូលដំបូង ហើយទំនិញធ្លាប់លក់គិតពីការលក់ចេញចុងក្រោយ។",
      reportReorder: "ផែនការបញ្ជាទិញឡើងវិញ",
      reportPurchasesSuppliers: "ការទិញ និងអ្នកផ្គត់ផ្គង់",
      reportCashPayments: "សាច់ប្រាក់ និងការទូទាត់",
      reportExpenseTrends: "និន្នាការចំណាយ",
      reportDeliveryPerformance: "លទ្ធផលដឹកជញ្ជូន",
      reportStaffPerformance: "លទ្ធផលបុគ្គលិក",
      reportReturnsExchanges: "ការបង្វិល និងប្តូរ",
      reportCustomerValue: "តម្លៃអតិថិជន",
      customerDebtDescription: "មើលចំនួនដែលអតិថិជនម្នាក់ៗជំពាក់ និងរយៈពេលដែលមិនទាន់បង់។",
      productPerformanceDescription: "ប្រៀបធៀបចំនួនលក់ ចំណូល ថ្លៃដើម ចំណេញ ការបង្វិល និងការប្តូរតាមទំនិញ ទំហំ និងពណ៌។",
      inventoryValueDescription: "មើលចំនួនបច្ចុប្បន្ន ថ្លៃដើមមធ្យម និងតម្លៃសរុបក្នុងស្តុក។",
      deadStockDescription: "រកទំនិញដែលនៅក្នុងស្តុកតែមិនលក់ និងមើលទឹកប្រាក់ដែលជាប់ក្នុងស្តុក។",
      reorderDescription: "ប៉ាន់ស្មានស្តុកនៅសល់ និងចំនួនដែលគួរបញ្ជាទិញឡើងវិញតាមការលក់ថ្មីៗ។",
      purchasesSuppliersDescription: "ប្រៀបធៀបចំណាយអ្នកផ្គត់ផ្គង់ ថ្លៃទិញ ថ្លៃដឹក និងការប្រែប្រួលថ្លៃតាមពេលវេលា។",
      cashPaymentsDescription: "ពិនិត្យសាច់ប្រាក់ ការផ្ទេរធនាគារ ការទូទាត់ផ្សេងៗ និងប្រាក់បង្វិលសម្រាប់បិទបញ្ជីប្រចាំថ្ងៃ។",
      expenseTrendsDescription: "ប្រៀបធៀបប្រភេទចំណាយតាមពេលវេលា និងសម្គាល់ចំណាយខ្ពស់ខុសធម្មតា។",
      deliveryPerformanceDescription: "ប្រៀបធៀបការដឹកជោគជ័យ ការបង្វិល ថ្លៃអតិថិជន និងថ្លៃក្រុមហ៊ុន។",
      staffPerformanceDescription: "ពិនិត្យការលក់ ចំណេញ បញ្ចុះតម្លៃ ការលុប ការកែស្តុក និងការទូទាត់តាមបុគ្គលិក។",
      returnsExchangesDescription: "រកទំនិញ ទំហំ និងពណ៌ដែលត្រូវបានបង្វិល ឬប្តូរញឹកញាប់។",
      customerValueDescription: "ប្រៀបធៀបការបញ្ជាទិញ ចំណូល ចំណេញ តម្លៃបញ្ជាទិញមធ្យម និងបំណុលរបស់អតិថិជន។",
      ordersCol: "ការបញ្ជាទិញ",
      revenueCol: "ចំណូល",
      profitCol: "ចំណេញ",
      noChannels: "គ្មានការលក់ក្នុងរយៈពេលនេះ។",
      stockFrom: "ពី",
      stockTo: "ដល់",
      allReasons: "គ្រប់ប្រភេទ",
      itemCol: "ទំនិញ",
      inOutCol: "ចូល / ចេញ",
      byCol: "ដោយ",
      noMovements: "គ្មានចលនាស្តុកក្នុងរយៈពេលនេះ។",
      exportCsv: "នាំចេញ CSV",
      csvDay: "ថ្ងៃ",
      exportDone: "ឯកសាររបាយការណ៍បានទាញយក។",
      reorderAsOf: "គិតត្រឹម {day}",
      lookbackWindow: "ចំណុចលក់",
      targetCover: "ថ្ងៃគ្រប់ដណ្តប់",
      daysUnit: "{days} ថ្ងៃ",
      unitsSoldInWindow: "លក់ក្នុងចំណុច",
      avgDailyUnits: "មធ្យម / ថ្ងៃ",
      daysRemainingCol: "ថ្ងៃនៅសល់",
      suggestedReorderQty: "ចំនួนគួរបញ្ជា",
      estimatedReorderCost: "ចំណាយប៉ាន់ស្មាន",
      reorderTotalsUnits: "ចំនួនត្រូវបញ្ជា",
      reorderTotalsVariants: "ពូជត្រូវបញ្ជា",
      reorderHint:
        "ចំនួនគួរបញ្ជា = ការលក់មធ្យមក្នុងមួយថ្ងៃ (តាមចំណុចលក់) × ថ្ងៃគ្រប់ដណ្តប់ − ស្តុកបច្ចុប្បន្ន។ ពូជដែលគ្មានការលក់ថ្មីៗមិនបង្ហាញទេ — សូមពិនិត្យនៅផ្នែកស្តុកស្លាប់ជំនួសវិញ។",
      reorderEmpty: "ឥឡូវគ្មានអ្វីត្រូវបញ្ជាទិញបន្ថែមទេ។",
    },
    dashboard: {
      todayTitle: "ថ្ងៃនេះ",
      // Welcome greeting with the staff member's first name, by time of day.
      greetingMorning: "អរុណសួស្តី, {name}",
      greetingAfternoon: "ទិវាសួស្តី, {name}",
      greetingEvening: "សាយណ្ហសួស្តី, {name}",
      // The range filter chips (Today reuses todayTitle).
      range7d: "៧ ថ្ងៃ",
      range30d: "៣០ ថ្ងៃ",
      rangeMtd: "ខែនេះ",
      rangeYtd: "ឆ្នាំនេះ",
      // The five KPI cards.
      kpiSales: "លក់",
      kpiPurchases: "ទិញចូល",
      kpiSalesDue: "ប្រាក់ជំពាក់",
      kpiInvoices: "វិក្កយបត្រ",
      kpiProfit: "ចំណេញ",
      chartSalesPurchases: "ការលក់ និងការទិញចូល",
      topProductsTitle: "ផលិតផលលក់ដាច់ជាងគេ",
      topProductsEmpty: "មិនទាន់មានការលក់ក្នុងរយៈពេលនេះទេ។",
      topCustomersTitle: "អតិថិជនកំពូល",
      topCustomersEmpty: "មិនទាន់មានការទូទាត់ក្នុងរយៈពេលនេះទេ។",
      other: "ផ្សេងៗ",
      stockValueTitle: "តម្លៃស្តុក",
      stockUnits: "{n} ដុំ",
      recentSalesTitle: "ការលក់ថ្មីៗ",
      recentSalesEmpty: "មិនទាន់មានការបញ្ជាទិញក្នុងរយៈពេលនេះទេ។",
      timeJustNow: "ទើបតែពេលនេះ",
      timeMinutesAgo: "{n} នាទីមុន",
      timeHoursAgo: "{n} ម៉ោងមុន",
      timeDaysAgo: "{n} ថ្ងៃមុន",
      timeDayAgo: "1 ថ្ងៃមុន",
      lowStockTitle: "ស្តុកទាប",
      lowStockEmpty: "ស្តុកគ្រប់គ្រាន់។",
      quickActions: "សកម្មភាពរហ័ស",
      setupTitle: "សូមដំឡើងព័ត៌មានហាងជាដំបូង",
      setupBody:
        "សូមស្វាគមន៍! បន្ថែមឈ្មោះហាង រូបិយបណ្ណ និងតំបន់ពេលវេលាក្នុងការកំណត់ បន្ទាប់មកផ្ទាំងតាមដាននឹងដំណើរការ។",
      setupCta: "បើកការកំណត់",
      qaNewSale: "លក់ថ្មី",
      qaNewPurchase: "ទិញចូលថ្មី",
      qaNewExpense: "ចំណាយថ្មី",
      qaDelivery: "របាយការណ៍ដឹក",
      qaStock: "ស្តុក",
      qaAdjustment: "កែតម្រូវស្តុក",
      qaStocktake: "រាប់ស្តុក",
      viewAllUnpaid: "មើលទាំងអស់",
      reminder: "រំលឹកបង់ប្រាក់",
      reminderMessage:
        "សួស្តី {name} នេះជា {shop}។ ការបញ្ជាទិញ {code} នៅសល់ {amount} មិនទាន់បានបង់។ អរគុណ!",
      copy: "ចម្លងសារ",
      copied: "បានចម្លង។",
      openWhatsApp: "WhatsApp",
      openTelegram: "Telegram",
    },
    deliveryCompanies: {
      addCompany: "បន្ថែមក្រុមហ៊ុនដឹកជញ្ជូន",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…",
      nameHint: "ឧ. Virak Buntham",
      phone: "ទូរស័ព្ទ",
      phoneHint: "ស្រេចចិត្ត។ ក្រុមហ៊ុនមិនចូលប្រើកម្មវិធីទេ — ទុកសម្រាប់ទូរស័ព្ទទាក់ទង។",
      defaultFee: "ថ្លៃលំនាំដើម (ដែលអ្នកបង់)",
      defaultFeeHint:
        "បំពេញដោយស្វ័យប្រវត្តិក្នុងការបញ្ជាទិញ ពេលជ្រើសក្រុមហ៊ុននេះ។ អាចកែតាមការបញ្ជាទិញនីមួយៗ។",
      created: "បានបន្ថែមក្រុមហ៊ុនដឹកជញ្ជូន។",
      saved: "បានរក្សាទុកក្រុមហ៊ុនដឹកជញ្ជូន។",
      newTitle: "ក្រុមហ៊ុនដឹកជញ្ជូនថ្មី",
      editTitle: "កែប្រែក្រុមហ៊ុនដឹកជញ្ជូន",
      activeHint: "បិទដើម្បីលាក់ក្រុមហ៊ុននេះពេលបង្កើតការលក់។",
      notFoundTitle: "រកមិនឃើញក្រុមហ៊ុនដឹកជញ្ជូន",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
      moduleOffTitle: "ម៉ូឌុលដឹកជញ្ជូនបានបិទ",
      moduleOffBody: "ក្រុមហ៊ុនត្រូវបានរក្សាទុក ប៉ុន្តែលាក់នៅពេលគិតលុយ។ បើកវានៅការកំណត់ហាង។",
    },
    purchases: {
      addPurchase: "ការទិញចូលថ្មី",
      searchPlaceholder: "ស្វែងរកតាមលេខកូដ…",
      allStatuses: "គ្រប់ស្ថានភាព",
      code: "លេខកូដ",
      createdLabel: "បានបង្កើត",
      supplier: "អ្នកផ្គត់ផ្គង់",
      items: "ទំនិញ",
      totalCost: "តម្លៃសរុប",
      newTitle: "ការទិញចូលថ្មី",
      editTitle: "កែប្រែការទិញចូល",
      supplierHint: "អ្នកដែលលក់ស្តុកនេះឱ្យអ្នក។",
      purchasedDate: "កាលបរិច្ឆេទទិញ",
      arrivalDate: "កាលបរិច្ឆេទមកដល់",
      arrivalDateHint:
        "ទុកទទេពេលទំនិញនៅតាមផ្លូវ។ បញ្ចូលកាលបរិច្ឆេទមកដល់ដើម្បីសម្គាល់ថាការទិញបានមកដល់ — ស្តុកនឹងចូលនៅថ្ងៃនោះ។",
      notesHint: "អ្វីដែលចង់ចាំអំពីការទិញនេះ។",
      quickAddSupplier: "អ្នកផ្គត់ផ្គង់ថ្មី",
      quickAddSupplierHint: "រក្សាទុកហើយវានឹងត្រូវបានជ្រើសរើសសម្រាប់ការទិញនេះ។",
      linesTitle: "ទំនិញ",
      linesHint: "ជ្រើសរើសទំនិញ បន្ទាប់មកកំណត់ចំនួន និងតម្លៃដើមសម្រាប់ទំហំដែលអ្នកត្រូវការ។",
      pickProduct: "ជ្រើសរើសទំនិញ…",
      pickSize: "ជ្រើសរើសទំហំ",
      pickColor: "ជ្រើសរើសពណ៌",
      product: "ទំនិញ",
      size: "ទំហំ",
      color: "ពណ៌",
      qty: "ចំនួន",
      unitCost: "តម្លៃដើមពីអ្នកផ្គត់ផ្គង់",
      costAfterDelivery: "ថ្លៃដើមក្រោយបូកដឹកជញ្ជូន",
      applyToAll: "អនុវត្តគ្រប់ទំហំ",
      addLine: "បន្ថែមបន្ទាត់",
      saveItem: "រក្សាទុកទំនិញ",
      addItemTitle: "បន្ថែមទំនិញ",
      editItemTitle: "កែប្រែទំនិញ",
      emptyLines: "មិនទាន់មានទំនិញ — បន្ថែមបន្ទាត់ដំបូងខាងលើ។",
      totalPieces: "សរុបទំនិញ",
      orderSummary: "សង្ខេបការបញ្ជាទិញ",
      itemsCost: "ថ្លៃទំនិញ",
      deliveryCost: "ថ្លៃដឹកជញ្ជូន",
      deliveryCostHint: "បញ្ចូលដោយស្វ័យប្រវត្តិទៅក្នុងទំនិញទាំងអស់ ពេលគណនាថ្លៃដើមទំនិញ។",
      deliveryPerPiece: "ថ្លៃដឹកជញ្ជូនក្នុងមួយ",
      otherCost: "ចំណាយផ្សេងៗ",
      grandTotal: "សរុបទាំងអស់",
      created: "បានបង្កើតការទិញចូល។",
      saved: "បានរក្សាទុកការទិញចូល។",
      notArrived: "មិនទាន់មកដល់",
      arrived: "បានមកដល់",
      stockInOn: "ស្តុកចូលនៅថ្ងៃ {value}",
      notFoundTitle: "រកមិនឃើញការទិញចូល",
      notFoundBody: "សូមត្រឡប់ទៅបញ្ជីវិញ។",
      needLines: "សូមបន្ថែមទំនិញយ៉ាងតិចមួយមុនពេលរក្សាទុក។",
      invalidLines: "ជួរខ្លះមិនបានបំពេញត្រឹមត្រូវ — សូមពិនិត្យចំនួន តម្លៃដើម និងតម្លៃលក់។",
      needSupplier: "សូមជ្រើសរើសអ្នកផ្គត់ផ្គង់ជាមុនសិន។",
      arrivalBeforePurchase: "កាលបរិច្ឆេទមកដល់មិនអាចមុនកាលបរិច្ឆេទទិញបានទេ។",
      priceWillChange: "តម្លៃលក់ប្តូរទៅ {value}",
      unarriveTitle: "ដកកាលបរិច្ឆេទមកដល់?",
      unarriveBody: "វានឹងដកស្តុកដែលការទិញនេះបាននាំចូលចេញពីធ្នើររបស់អ្នក។",
      stockInTitle: "ស្តុកចូលពីការទិញនេះ",
      stockInHint: "ទំនិញទាំងអស់ដែលការទិញនេះបាននាំចូល។ ការកែបន្ទាត់នឹងធ្វើបច្ចុប្បន្នភាពជួរទាំងនេះ។",
    },
    channels: {
      addChannel: "បន្ថែមទំព័រលក់",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…",
      nameHint: "ឧ. Facebook — Doly Outfits",
      type: "ប្រភេទ",
      typeHint: "ប្រើសម្រាប់ដាក់ក្រុមការលក់ក្នុងរបាយការណ៍។",
      created: "បានបន្ថែមទំព័រលក់។",
      saved: "បានរក្សាទុកទំព័រលក់។",
      newTitle: "ទំព័រលក់ថ្មី",
      editTitle: "កែប្រែទំព័រលក់",
      activeHint: "បិទដើម្បីលាក់ទំព័រនេះពេលបង្កើតការលក់។",
      notFoundTitle: "រកមិនឃើញទំព័រលក់",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
      types: {
        facebook: "Facebook",
        instagram: "Instagram",
        tiktok: "TikTok",
        walk_in: "ដើរចូលហាង",
        custom: "ផ្សេងៗ",
      },
    },
    customers: {
      addCustomer: "បន្ថែមអតិថិជន",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ ឬទូរស័ព្ទ…",
      nameHint: "ឧ. សុខា ញឹម",
      phone: "ទូរស័ព្ទ",
      phoneHint: "លេខប៉ុណ្ណោះ — ប្រើដើម្បីរកអតិថិជនឱ្យលឿនពេលលក់។",
      address: "អាសយដ្ឋាន",
      addressHint: "កន្លែងដឹកជញ្ជូន។ ស្រេចចិត្ត។",
      notes: "កំណត់ចំណាំ",
      notesHint: "ទំហំដែលចូលចិត្ត កន្លែងដឹក អ្វីដែលចង់ចាំ។",
      created: "បានបន្ថែមអតិថិជន។",
      saved: "បានរក្សាទុកអតិថិជន។",
      newTitle: "អតិថិជនថ្មី",
      editTitle: "កែប្រែអតិថិជន",
      activeHint: "បិទដើម្បីលាក់អតិថិជននេះពេលលក់។",
      notFoundTitle: "រកមិនឃើញអតិថិជន",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
      duplicateTitle: "អតិថិជននេះមានរួចហើយ",
      duplicateBody: "មានអតិថិជនដែលប្រើលេខទូរស័ព្ទនេះរួចហើយ។ សូមប្រើអតិថិជនដែលមានស្រាប់។",
      useExisting: "ប្រើដែលមានស្រាប់",
      existingSelected: "បានជ្រើសរើសអតិថិជនដែលមានស្រាប់។",
      owedTitle: "នៅជំពាក់",
      owedOrders: "{n} ការបញ្ជាទិញមិនទាន់បង់",
      owedEmpty: "អតិថិជននេះមិនមានប្រាក់ជំពាក់ទេ។",
      owedPaidOf: "បានបង់ {paid} ក្នុងចំណោម {total}",
    },
    stock: {
      searchPlaceholder: "ស្វែងរកទំនិញ…",
      variantSearchPlaceholder: "ស្វែងរកតាមទំហំ ពណ៌ ឬ SKU…",
      productCol: "ទំនិញ",
      variantsCol: "ប្រភេទ",
      availableStock: "ស្តុកមាន",
      statusCol: "ស្ថានភាព",
      lastUpdatedCol: "បច្ចុប្បន្នភាពចុងក្រោយ",
      lastMovementCol: "ចលនាចុងក្រោយ",
      variantCol: "ប្រភេទ",
      viewVariants: "មើលប្រភេទ",
      viewMovements: "មើលចលនា",
      statusInStock: "មានស្តុក",
      statusLowStock: "ស្តុកទាប",
      statusOutOfStock: "អស់ស្តុក",
      variantsSummary: "{n} ប្រភេទ",
      plusN: "+{n}",
      noColor: "គ្មានពណ៌",
      needsAttentionOne: "{n} ទំនិញត្រូវយកចិត្តទុកដាក់",
      needsAttentionMany: "{n} ទំនិញត្រូវយកចិត្តទុកដាក់",
      remaining: "នៅសល់ {n}",
      reorderLevel: "កម្រិតបញ្ជាទិញបន្ថែម៖ {n}",
      createPurchaseOrder: "បង្កើតការបញ្ជាទិញចូល",
      viewProduct: "មើលទំនិញ",
      viewAll: "មើលទាំងអស់",
      allStatuses: "ទាំងអស់",
      sortByQty: "តម្រៀបតាមចំនួន",
      clearFilters: "សម្អាតតម្រង",
      typeCol: "ប្រភេទ",
      movementCol: "ចលនា",
      referenceCol: "យោង",
      movementBalanceCol: "សមតុល្យ",
      referenceOrder: "បញ្ជាទិញ #{code}",
      referencePo: "PO #{code}",
      noMovements: "រកមិនឃើញចលនាស្តុកសម្រាប់ប្រភេទនេះទេ។",
      filteredEmpty: "គ្មានប្រភេទណាត្រូវនឹងតម្រងរបស់អ្នកទេ។",
      adjustStock: "កែស្តុក",
      currentStock: "ស្តុកបច្ចុប្បន្ន៖ {n}",
      sizeCol: "ទំហំ",
      colorCol: "ពណ៌",
      skuCol: "SKU",
      qtyCol: "ក្នុងស្តុក",
      exportCsv: "នាំចេញ CSV",
      exportDone: "ឯកសារស្តុកបានទាញយក។",
      lowStockBadgeAria: "{n} ទំនិញស្តុកទាប",
      emptyHistory: "មិនទាន់មានចលនាទេ។",
      movedBy: "ដោយ",
      dateCol: "កាលបរិច្ឆេទ",
      reasonCol: "មូលហេតុ",
      notFoundTitle: "រកមិនឃើញទំនិញ",
      notFoundBody: "សូមត្រឡប់ទៅបញ្ជីស្តុកវិញ។",
      reasons: {
        purchase: "ទិញចូល",
        sale: "លក់ចេញ",
        return: "បង្វិលមកវិញ",
        exchange_out: "ផ្លាស់ចេញ",
        exchange_in: "ផ្លាស់ចូល",
        cancel: "បានលុប",
        adjustment: "កែតម្រូវ",
        stocktake: "រាប់ស្តុក",
      },
      actions: {
        purchase: "បានទទួលស្តុក",
        sale: "បានលក់តាមការបញ្ជាទិញ",
        return: "បានបង្វិលទៅស្តុក",
        exchange_out: "បានផ្លាស់ចេញ",
        exchange_in: "បានផ្លាស់ចូល",
        cancel: "បានលុប — បង្វិលទៅស្តុក",
        adjustment: "កែតម្រូវស្តុក",
        stocktake: "រាប់ស្តុក",
      },
      openingStock: "ស្តុកដើម",
      stockIn: "ស្តុកចូល",
      stockOut: "ស្តុកចេញ",
      closingStock: "ស្តុកបញ្ចប់",
      allSigns: "គ្រប់ទិស",
      allUsers: "បុគ្គលិកទាំងអស់",
      balanceCol: "តុល្យភាព",
      stockCol: "ស្តុក",
      netCol: "សុទ្ធ",
      unitCost: "ថ្លៃដើម",
      showMovements: "បង្ហាញចលនា {n}",
      showMovementsOne: "បង្ហាញចលនា {n}",
      hideMovements: "លាក់ចលនា",
      openingAtRange: "ស្តុកដើមនៅ {day}",
      stockInDuring: "ស្តុកចូលក្នុងរយៈពេល",
      stockOutDuring: "ស្តុកចេញក្នុងរយៈពេល",
      closingAtRange: "ស្តុកបញ្ចប់នៅ {day}",
      currentStockBare: "ស្តុកបច្ចុប្បន្ន",
      currentStockToday: "ស្តុកបច្ចុប្បន្នថ្ងៃនេះ: {n}",
      noStockChange: "មិនមានការប្រែប្រួលស្តុក",
      movementFlow: "លំហូរចលនា",
      movementFlowOrder: "ចាស់ → ថ្មី",
      combined: {
        saleCancel: "បានលក់ និងបានលុប",
        returnAdjustment: "បានបង្វិល និងខូចខាត",
      },
      operations: {
        purchase: "បានទទួលស្តុក",
        sale: "បានបង្កើតការលក់",
        return: "បានបង្វិលទំនិញ",
        exchange_out: "បានផ្លាស់ប្តូរទំនិញ",
        exchange_in: "បានផ្លាស់ប្តូរទំនិញ",
        cancel: "បានលុបទំនិញ",
        adjustment: "កែតម្រូវស្តុក",
        stocktake: "រាប់ស្តុក",
      },
      flowDiagnostic:
        "ការវិនិច្ឆ័យលំហូរចលនា — ខ្សែសង្វាក់តុល្យភាពនៃប្រតិបត្តិការនេះមិនពេញលេញទេ។",
      sortNewestFirst: "ថ្មីបំផុតមុន",
      sortOldestFirst: "ចាស់បំផុតមុន",
      integrityWarning:
        "តុល្យភាពស្តុកមិនត្រូវគ្នា — សៀវភៅបង្ហាញ {expected} ទិដ្ឋភាពនេះបង្ហាញ {actual}។",
    },
    adjustments: {
      quickTitle: "បញ្ចូល/បង្ហូរស្តុករហ័ស",
      quickHint: "បន្ថែមឬដកដុំដោយដៃ — ខូច រកឃើញ ចែកគេ…",
      stocktakeTitle: "រាប់ស្តុកទាំងអស់",
      stocktakeHint:
        "រាប់របស់នៅលើធ្នើរពិតប្រាកដ រួចរក្សាទុក។ ភាពខុសគ្នានឹងត្រូវកត់ត្រាជាចលនាស្តុក។",
      searchItems: "ស្វែងរកទំនិញ…",
      pickItem: "ទំនិញ",
      noItems: "រកមិនឃើញទំនិញ។",
      inStock: "ក្នុងស្តុក",
      stockIn: "បញ្ចូលស្តុក",
      stockOut: "បង្ហូរស្តុក",
      qty: "ចំនួន",
      reasonNote: "មូលហេតុ / កំណត់ចំណាំ",
      reasonNoteHint: "ហេតុអ្វីស្តុកនេះផ្លាស់ប្តូរ — បង្ហាញក្នុងប្រវត្តិ។",
      reasonDamaged: "ខូច",
      reasonFound: "រកឃើញ",
      reasonGiveaway: "ចែកគេ",
      saveAdjustment: "រក្សាទុក",
      adjustmentSaved: "បានរក្សាទុកការកែស្តុក។",
      pickFirst: "ជ្រើសទំនិញសិន។",
      needNote: "បញ្ជាក់ហេតុផល។",
      notEnough: "ក្នុងស្តុកមានតែ {n} ។",
      countedCol: "ចំនួនរាប់",
      changesCount: "{n} ផ្លាស់ប្តូរ",
      saveStocktake: "រក្សាទុកការរាប់",
      stocktakeSaved: "បានកែ {n} បន្ទាត់។",
      recentTitle: "ការកែស្តុកថ្មីៗ",
      recentEmpty: "មិនទាន់មានការកែស្តុក។",
      selectItemHint: "ចុចជ្រើសទំនិញ រួចជ្រើសបញ្ចូលឬបង្ហូរ។",
    },
    products: {
      addProduct: "បន្ថែមទំនិញ",
      searchPlaceholder: "ស្វែងរកតាមឈ្មោះ…",
      allCategories: "គ្រប់ប្រភេទ",
      newTitle: "ទំនិញថ្មី",
      editTitle: "កែប្រែទំនិញ",
      nameHint: "ឧ. អាវខ្លី",
      description: "ការពណ៌នា",
      descriptionHint: "បង្ហាញលើទំព័រការលក់។ ស្រេចចិត្ត។",
      category: "ប្រភេទ",
      categoryHint: "ស្រេចចិត្ត។ ប្រើសម្រាប់តម្រៀប និងតម្រងទំនិញ។",
      code: "កូដ",
      codeHint: "លេខកូដទំនិញផ្ទាល់ខ្លួនរបស់អ្នក — បង្ហាញលើកាត POS ជាប់ SKU។ ស្រេចចិត្ត។",
      defaultPrice: "តម្លៃលក់ដើម",
      defaultPriceHint: "ចម្លងទៅគ្រប់ទំហំ និងពណ៌។ អាចកែដោយឡែកក្រោយបាន។",
      defaultCost: "ថ្លៃដើមយោង",
      defaultCostHint: "តម្លៃទិញចូលធម្មតា។ បំពេញដោយស្វ័យប្រវត្តិពេលទិញចូល។",
      hasColors: "មានពណ៌",
      hasColorsHint: "បើក = ទំហំ × ពណ៌។ បិទ = តែទំហំ។",
      sizes: "ទំហំ",
      sizesHint: "វាយទំហំរួចចុច Enter ឧ. S, M, L, XL។",
      colors: "ពណ៌",
      colorsHint: "វាយពណ៌រួចចុច Enter ឧ. ខ្មៅ ស។",
      addTag: "បន្ថែម",
      photo: "រូបថតទំនិញ",
      photoHint: "បង្ហាញក្នុងបញ្ជីទំនិញ និងទំព័រលក់។",
      uploadPhoto: "បង្ហោះរូបថត",
      replacePhoto: "ផ្លាស់ប្តូរ",
      removePhoto: "លុបរូបថត",
      invalidMoney: "សូមបញ្ចូលចំនួនដូច 12.50",
      invalidImage: "សូមជ្រើសរើសឯកសាររូបភាព (អតិបរមា 10 MB)។",
      created: "បានបន្ថែមទំនិញ។",
      saved: "បានរក្សាទុកទំនិញ។",
      activeHint: "បិទដើម្បីលាក់ទំនិញនេះពីការលក់ថ្មី។",
      notFoundTitle: "រកមិនឃើញទំនិញ",
      notFoundBody: "វាប្រហែលត្រូវបានបិទ។ សូមត្រឡប់ទៅបញ្ជីវិញ។",
      variantsTitle: "ទំហំ និងពណ៌",
      variantsHint:
        "តម្លៃចាប់ផ្តើមពីតម្លៃដើម។ វាយតម្លៃថ្មីដើម្បីប្តូរ — ទុកទទេ = ត្រឡប់ទៅតម្លៃដើមវិញ។",
      variantsSyncHint:
        "ការផ្លាស់ប្តូរទំហំ ឬពណ៌ នឹងបន្ថែមថ្មី និងលាក់ចាស់។ ប្រវត្តិស្តុកត្រូវបានរក្សាទុក។",
      selectAll: "ជ្រើសទាំងអស់",
      clearSelection: "សម្អាត",
      selectedCount: "បានជ្រើស",
      applyTo: "កំណត់សម្រាប់ដែលបានជ្រើស៖",
      applyPrice: "អនុវត្តតម្លៃលក់",
      applyCost: "អនុវត្តថ្លៃដើម",
      clearOverrides: "លុបការកែ",
      applied: "បានធ្វើបច្ចុប្បន្នភាព។",
      custom: "កែដោយឡែក",
      sku: "SKU",
      skuHint: "លេខកូដស្រេចចិត្ត។",
      priceCol: "តម្លៃលក់",
      costCol: "ថ្លៃដើម",
    },
    sales: {
      newSale: "ការលក់ថ្មី",
      filterHint: "ជ្រើសរើសតែអ្វីដែលអ្នកត្រូវការ រួចបិទផ្ទាំងនេះ។",
      searchProducts: "ស្វែងរកទំនិញ…",
      noProducts: "រកមិនឃើញទំនិញទេ។",
      noProductsInStock: "គ្មានទំនិញក្នុងស្តុកទេ។",
      allSizes: "គ្រប់ទំហំ",
      category: "ប្រភេទ",
      allCategories: "គ្រប់ប្រភេទ",
      clearFilters: "សម្អាតតម្រង",
      pickProductHint: "ជ្រើសទំហំ (និងពណ៌) រួចចុចបន្ថែម។",
      size: "ទំហំ",
      color: "ពណ៌",
      inStock: "ក្នុងស្តុក",
      outOfStock: "អស់ស្តុក",
      addToCart: "បន្ថែម",
      cart: "កន្ត្រក",
      cartEmpty: "កន្ត្រកទទេ — បន្ថែមទំនិញដើម្បីចាប់ផ្តើមការលក់។",
      viewCart: "មើលកន្ត្រក",
      item: "ទំនិញ",
      qty: "ចំនួន",
      sku: "SKU",
      code: "កូដ",
      price: "តម្លៃ",
      itemDiscount: "បញ្ចុះតម្លៃទំនិញ",
      remove: "ដកចេញ",
      itemsCount: "ទំនិញ",
      subtotal: "សរុបរង",
      customer: "អតិថិជន",
      selectCustomer: "ជ្រើសរើសអតិថិជន",
      walkInCustomer: "អតិថិជនចូលហាង",
      customerHint: "អ្នកណាទិញ? ជ្រើសអតិថិជនដែលមាន ឬបង្កើតថ្មី។",
      searchCustomers: "ស្វែងរកតាមឈ្មោះ ឬទូរស័ព្ទ…",
      newCustomer: "អតិថិជនថ្មី",
      noCustomers: "រកមិនឃើញអតិថិជនទេ។",
      addAddress: "បន្ថែមអាសយដ្ឋាន",
      addressSaved: "បានរក្សាទុកអាសយដ្ឋាន។",
      channel: "ទំព័រលក់",
      channelHint: "ការបញ្ជាទិញនេះមកពីទំព័រមួយណា?",
      delivery: "ដឹកជញ្ជូន",
      location: "អាសយដ្ឋាន",
      company: "ក្រុមហ៊ុន",
      noCompany: "ខ្លួនឯង / ទទួលនៅហាង",
      companyFee: "ថ្លៃអតិថិជន",
      companyCost: "ថ្លៃក្រុមហ៊ុន",
      companyCostHint: "អ្វីដែលអ្នកបង់ឱ្យក្រុមហ៊ុនសម្រាប់ការបញ្ជាទិញនេះ។",
      orderDiscount: "បញ្ចុះតម្លៃការបញ្ជាទិញ",
      orderDiscountHint: "សម្រាប់ការបញ្ជាទិញទាំងមូល។ ស្រេចចិត្ត។",
      payment: "ការបង់ប្រាក់",
      method: "វិធីសាស្ត្រ",
      methods: { cash: "សាច់ប្រាក់", bank_transfer: "ធនាគារ", other: "ផ្សេងទៀត", refund: "បង្វិលប្រាក់" },
      amountReceived: "ចំនួនដែលទទួល",
      paymentDate: "កាលបរិច្ឆេទបង់ប្រាក់",
      paymentNote: "កំណត់ចំណាំការបង់ប្រាក់",
      paymentNoteHint: "រក្សាទុកជាមួយការបង់ប្រាក់ — ឃើញក្នុងប្រវត្តិការបង់ប្រាក់។",
      saleNote: "កំណត់ចំណាំការលក់",
      saleNoteHint: "កំណត់ចំណាំស្រេចចិត្តលើការបញ្ជាទិញ។",
      notPaid: "មិនទាន់បង់",
      remaining: "នៅសល់",
      changeDue: "ប្រាក់អាប់",
      total: "សរុប",
      paid: "បានបង់",
      unpaid: "មិនទាន់បង់",
      partial: "បង់ខ្លះ",
      completeSale: "បញ្ចប់ការលក់",
      totalPayable: "សរុបត្រូវបង់",
      payNow: "បង់ឥឡូវ",
      home: "ទំព័រដើម",
      reset: "កំណត់ឡើងវិញ",
      refreshProducts: "ផ្ទុកទំនិញឡើងវិញ",
      paymentCheckout: "ការទូទាត់",
      transactionSummary: "សង្ខេបប្រតិបត្តិការ",
      totalAmount: "ចំនួនសរុប",
      completePayment: "បញ្ចប់ការទូទាត់",
      saleDate: "កាលបរិច្ឆេទលក់",
      paymentType: "ប្រភេទការបង់ប្រាក់",
      paidAmount: "ចំនួនដែលបានបង់",
      customerInfo: "ព័ត៌មានអតិថិជន",
      reviewSale: "ពិនិត្យការលក់",
      reviewSaleHint: "ពិនិត្យអ្វីៗទាំងអស់មុនពេលបញ្ចប់ការបញ្ជាទិញ។",
      confirmCompleteSale: "បញ្ជាក់ និងបញ្ចប់ការលក់",
      back: "ត្រឡប់ក្រោយ",
      tax: "ពន្ធ",
      saleCreated: "ការលក់ {code} បានបង្កើត។",
      invoice: "វិក្កយបត្រ",
      print: "បោះពុម្ព",
      printReceipt: "វិក្កយបត្រ (កម្ដៅ)",
      printLabel: "ស្លាកកញ្ចប់",
      printA5: "វិក្កយបត្រ A5",
      receiptSent: "បានផ្ញើវិក្កយបត្រទៅម៉ាស៊ីនពុម្ព។",
      labelSent: "បានផ្ញើស្លាកកញ្ចប់ទៅម៉ាស៊ីនពុម្ព។",
      printHint:
        "ដំឡើងម៉ាស៊ីនពុម្ព ៨០មម នៅក្នុងការកំណត់ ដើម្បីបោះពុម្ពវិក្កយបត្រ និងស្លាកកញ្ចប់។",
      close: "បិទ",
      order: "ការបញ្ជាទិញ",
      date: "កាលបរិច្ឆេទ",
      by: "ដោយ",
      signature: "ហត្ថលេខា",
      thankyou: "អរគុណសម្រាប់ការគាំទ្រពួកយើង <3",
      deliveryFee: "ថ្លៃដឹកជញ្ជូន",
      deliveryFeeHint: "គិតលើអតិថិជន។ ស្រេចចិត្ត។",
      discount: "បញ្ចុះតម្លៃ",
      totalQty: "ចំនួនសរុប",
      profit: "ចំណេញ",
      createdBy: "បង្កើតដោយ",
      receivePayment: "ទទួលប្រាក់",
      refund: "បង្វិលប្រាក់",
      paymentHistory: "ប្រវត្តិការបង់ប្រាក់",
      orderHistory: "ប្រវត្តិការបញ្ជាទិញ",
      events: {
        created: "បានបង្កើតការបញ្ជាទិញ",
        statusChanged: "បានប្តូរស្ថានភាព",
        paymentReceived: "បានទទួលប្រាក់",
        refundGiven: "បានបង្វិលប្រាក់",
        linesAdjusted: "បានរក្សាទុកចំនួនដឹកជូន",
        itemSwapped: "បានប្តូរទំនិញ",
        itemAdded: "បានបន្ថែមទំនិញ",
        itemRemoved: "បានដកទំនិញចេញ",
        itemQtyChanged: "បានប្តូរចំនួន",
        itemsReturned: "បានទទួលទំនិញត្រឡប់",
        deliveryOutcome: "លទ្ធផលដឹកជញ្ជូន",
        deliveryCostChanged: "ថ្លៃដឹកជញ្ជូន",
        saleEdited: "កែសម្រួលការបញ្ជាទិញ",
        saleEditedFields: {
          customer: "អតិថិជន",
          channel: "ទំព័រលក់",
          deliveryCompany: "ក្រុមហ៊ុនដឹកជញ្ជូន",
          deliveryFee: "ថ្លៃអតិថិជន",
          deliveryCost: "ថ្លៃក្រុមហ៊ុន",
          discount: "បញ្ចុះតម្លៃ",
          note: "កំណត់សម្គាល់",
          price: "តម្លៃ",
          itemDiscount: "បញ្ចុះតម្លៃទំនិញ",
        },
      },
      adjustments: "ការកែតម្រូវការបញ្ជាទិញ",
      adjust: "កែតម្រូវ",
      adjustDeliveredTitle: "កែតម្រូវការដឹកជូន",
      adjustDeliveredHint:
        "តើអតិថិជនទទួលយកប៉ុន្មានដុំ? សល់ពីនេះនឹងត្រឡប់ចូលស្តុកវិញ។",
      deliveredQty: "ចំនួនដឹកជូន",
      returnedQty: "បានត្រឡប់មកវិញ",
      allDelivered: "ដឹកជូនទាំងអស់",
      returnAll: "ទទួលត្រឡប់ទាំងអស់",
      noneDelivered: "មិនទាន់ដឹកជូន",
      linesAdjusted: "បានរក្សាទុកចំនួនដឹកជូន។",
      itemAdded: "បានបន្ថែមទំនិញ។",
      itemRemoved: "បានដកទំនិញចេញ។",
      itemSwapped: "បានប្តូរទំនិញ។",
      returnItem: "ទទួលទំនិញត្រឡប់",
      returnItemTitle: "ទទួលទំនិញត្រឡប់",
      returnItemHint:
        "ទំនិញដែលអតិថិជនយកមកវិញនឹងចូលស្តុក។ ការបង្វិលប្រាក់គឺជាជំហានដាច់ដោយឡែកលើការបញ្ជាទិញនេះ។",
      returnQty: "ចំនួនដែលត្រឡប់",
      refundAmount: "ចំនួនប្រាក់បង្វិល",
      returnRefundHint: "ជម្រើស — កត់ត្រាប្រាក់ដែលបានបង្វិលឱ្យអតិថិជន។",
      itemsReturned: "បានទទួលទំនិញត្រឡប់។",
      nothingToReturn: "គ្មានទំនិញដើម្បីទទួលត្រឡប់ទេ — អតិថិជនមិនបានកាន់ទំនិញឡើយ។",
      // ការបង្វិល/កែតម្រូវដែលដឹកនាំ (ទំព័រកែសម្រួលការលក់ + ការពិនិត្យលុបចោល)។
      resolutionTitle: "តើមានអ្វីកើតឡើងចំពោះទំនិញទាំងនេះ?",
      resolutionHint:
        "អតិថិជនកំពុងកាន់ {qty}។ សូមជ្រើសរើសអ្វីដែលពិតជាកើតឡើង ដើម្បីឱ្យស្តុក និងវិក្ក័យបត្រនៅត្រឹមត្រូវ។",
      resolutionQty: "ចំនួន",
      resolutionReason: "មូលហេតុ",
      resolutionReasonPlaceholder: "តើពិតជាមានអ្វីកើតឡើង?",
      resolutionReasonRequired: "ត្រូវការមូលហេតុសម្រាប់ការកែតម្រូវនេះ។",
      resolutionRefund: "ប្រាក់បង្វិល",
      resolutionRefundHint: "ជម្រើស — ប្រាក់ដែលបានបង្វិលឱ្យអតិថិជន នឹងត្រូវបានកត់ត្រាជាប្រាក់បង្វិល។",
      resolutionCancel: "បោះបង់",
      resolutionConfirm: "បន្ថែមទៅការផ្លាស់ប្តូរ",
      outcomeReturnedSellable: "បង្វិលទៅស្តុកលក់វិញ",
      outcomeReturnedSellableHint: "ទំនិញបានត្រឡប់មក ហើយអាចលក់បានទៀត។",
      outcomeReturnedDamaged: "បានត្រឡប់ដោយខូចខាត",
      outcomeReturnedDamagedHint: "ទំនិញបានត្រឡប់មក ប៉ុន្តែមិនអាចលក់បាន — កត់ត្រាថាខូចខាត។",
      outcomeStillWithCustomer: "នៅជាមួយអតិថិជន",
      outcomeStillWithCustomerHint: "គ្មានអ្វីត្រូវបានបង្វិលទេ — ទំនិញនៅតែក្នុងវិក្ក័យបត្រ។",
      outcomeDeliveryIncorrect: "ការដឹកជញ្ជូនខុស — មិនដែលបានប្រគល់",
      outcomeDeliveryIncorrectHint:
        "ប្រព័ន្ធបង្ហាញថាបានដឹកជូន ប៉ុន្តែទំនិញមិនដែលចេញពីហាងទេ។ សម្រាប់ម្ចាស់ហាងតែប៉ុណ្ណោះ ដោយមានមូលហេតុ។",
      cancelReviewTitle: "លុបចោលការបញ្ជាទិញនេះ?",
      cancelReviewHint:
        "ទំនិញនីមួយៗដែលអតិថិជនកំពុងកាន់ ត្រូវការលទ្ធផលរូបវន្ត មុនពេលលុបចោលការបញ្ជាទិញនេះ។",
      cancelReviewStillHeld:
        "ទំនិញ {qty} នៅជាមួយអតិថិជន — សូមជ្រើសរើសអ្វីដែលកើតឡើងចំពោះពួកវា។",
      cancelReviewResolveAll: "សម្គាល់ទាំងអស់ថាបានបង្វិល",
      cancelReviewResolveAllDamaged: "សម្គាល់ទាំងអស់ថាខូចខាត",
      cancelReviewReason: "មូលហេតុនៃការលុបចោល",
      cancelReviewReasonPlaceholder: "ហេតុអ្វីបានជាលុបចោលការបញ្ជាទិញនេះ?",
      cancelled: "បានលុបចោលការបញ្ជាទិញ។",
      orderDetails: "ព័ត៌មានការបញ្ជាទិញ",
      expectedProfit: "ប្រាក់ចំណេញរំពឹងទុក",
      groupLines: "បន្ទាត់លក់ {n}",
      groupShowDetails: "បង្ហាញលម្អិត",
      groupHideDetails: "លាក់លម្អិត",
      groupMultiplePrices: "តម្លៃច្រើន",
      groupIntegrity: "សូមពិនិត្យទិន្នន័យ — បរិមាណទាំងនេះមិនត្រូវគ្នាទេ។",
      paymentSummaryTotal: "សរុបការបញ្ជាទិញ",
      paymentSummaryNetPaid: "បានបង់សុទ្ធ",
      paidInFull: "បានបង់ពេញ",
      refundDue: "ត្រូវបង្វិលប្រាក់",
      receivedRefunded: "បានទទួល {received} · បានបង្វិល {refunded}",
      refundConfirmTitle: "បង្វិលប្រាក់ {amount} ឱ្យអតិថិជន?",
      refundConfirmNetAfter: "បានបង់សុទ្ធបន្ទាប់ពីបង្វិល: {amount}",
      refundConfirmRemainingAfter: "នៅជំពាក់បន្ទាប់ពីបង្វិល: {amount}",
      noPaymentsYet: "មិនទាន់មានការទូទាត់ទេ",
      paymentReceived: "បានទទួលការទូទាត់",
      refundIssued: "បានចេញប្រាក់បង្វិល",
      stateAwaiting: "កំពុងរង់ចាំ {qty}",
      stateWithCustomer: "នៅជាមួយអតិថិជន {qty}",
      stateCancelled: "បានលុប {qty}",
      stateReturned: "បានបង្វិល {qty}",
      lineStateReturnedSellable: "បានបង្វិល · អាចលក់វិញ",
      markPending: "សម្គាល់ថាកំពុងរង់ចាំ",
      markPacked: "សម្គាល់ថាខ្ចប់រួច",
      markDelivering: "សម្គាល់ថាកំពុងដឹក",
      markDelivered: "សម្គាល់ថាដឹកជូនរួច",
      markPartiallyDelivered: "សម្គាល់ថាដឹកជូនមួយផ្នែក",
      cancelOrder: "បោះបង់ការបញ្ជាទិញ",
      cancelConfirmTitle: "បោះបង់ការបញ្ជាទិញនេះ?",
      cancelConfirmBody:
        "ទំនិញដែលមិនទាន់លក់នឹងត្រឡប់ចូលស្តុកវិញ។ សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយបានទេ។",
      keepShippingFee: "អតិថិជននៅតែបង់ថ្លៃដឹកជញ្ជូន",
      keepShippingFeeHint:
        "ធីកនៅពេលកញ្ចប់ត្រូវបានដឹកទៅរួចហើយ តែអតិថិជនមិនយកទំនិញ — ថ្លៃដឹកជញ្ជូននៅតែជំពាក់លើការបញ្ជាទិញដែលបានបោះបង់។",
      refundHint:
        "ប្រាក់ដែលបង្វិលទៅអតិថិជនវិញ កត់ត្រានៅទីនេះ។",
      paymentAdded: "បានទទួលប្រាក់។",
      refundAdded: "បានកត់ត្រាការបង្វិលប្រាក់។",
      statusUpdated: "បានធ្វើបច្ចុប្បន្នភាពស្ថានភាពការបញ្ជាទិញ។",
      allStatuses: "ស្ថានភាពទាំងអស់",
      today: "ថ្ងៃនេះ",
      allChannels: "ទំព័រទាំងអស់",
      searchCode: "ស្វែងរកវិក្កយបត្រ ឧ. 001…",
      view: "មើល",
      due: "ជំពាក់",
      fromDate: "ចាប់ពី",
      toDate: "ដល់",
      allPaymentStatuses: "ស្ថានភាពបង់ប្រាក់ទាំងអស់",
      editSale: "កែសម្រួលការលក់",
      updateStatus: "ប្តូរស្ថានភាព",
      status: "ស្ថានភាព",
      currentStatus: "ស្ថានភាពបច្ចុប្បន្ន",
      noStatusSteps: "មិនមានការប្តូរស្ថានភាពទេ។",
      statusNow: "ឥឡូវ",
      statusPickHint:
        "ជ្រើសរើសស្ថានភាពបច្ចុប្បន្នរបស់ការបញ្ជាទិញនេះ។ ជំហានពណ៌ប្រផេះមិនអាចប្រើពីទីនេះបានទេ។",
      partiallyDeliveredHint:
        "អតិថិជនយកតែមួយផ្នែកនៅពេលដឹកជូន — ទំនិញនៅសល់ត្រឡប់ចូលស្តុកវិញ។",
      saleDetail: "ព័ត៌មានលម្អិត",
      saleReturn: "ប្រគល់ទំនិញវិញ",
      showPayments: "មើលការបង់ប្រាក់",
      createPayment: "បង្កើតការបង់ប្រាក់",
      cancelSale: "បោះបង់ការលក់",
      paymentStatus: "ស្ថានភាពការបង់ប្រាក់",
      paymentStatuses: {
        paid: "បានបង់",
        partlyPaid: "បង់មួយផ្នែក",
        unpaid: "មិនទាន់បង់",
      },
      saleEdited: "បានកែសម្រួលការលក់។",
      paymentAddedWithChange: "បានទទួលប្រាក់។ ប្រាក់អាប់: {amount}។",
      cancelPaidHint:
        "ការបញ្ជាទិញនេះបានបង់ {amount} ហើយ — សូមបង្វិលប្រាក់វិញបន្ទាប់ពីបោះបង់។",
      notFoundTitle: "រកមិនឃើញការបញ្ជាទិញ",
      notFoundBody: "ការបញ្ជាទិញនេះមិនមានទេ។",
      itemQtys: {
        ordered: "បានបញ្ជាទិញ",
        delivered: "បានដឹកជូន",
        cancelled: "បានបោះបង់",
        returned: "បានបង្វិល",
        withCustomer: "អតិថិជនមាន",
        notDeliveredYet: "រង់ចាំការដឹកជូន",
        saleLineSku: "ទំនិញ / SKU",
      },
      emptyHistory: "មិនទាន់មានអ្វីនៅឡើយ។",
      // ទំព័រកែសម្រួលការបញ្ជាទិញ — ស្តុកមិនផ្លាស់ប្តូរទេ រហូតដល់ចុចរក្សាទុក។
      edit: {
        title: "កែសម្រួលការលក់",
        breadcrumb: "ការលក់",
        breadcrumbEdit: "កែសម្រួល",
        orderCard: "ព័ត៌មានការបញ្ជាទិញ",
        orderCardHint: "ការបញ្ជាទិញនេះសម្រាប់អ្នកណា និងមកពីទំព័រណា។",
        itemsCard: "ទំនិញ",
        itemsCardHint:
          "ប្តូរចំនួន តម្លៃ ឬបញ្ចុះតម្លៃ។ ស្តុកផ្លាស់ប្តូរតែពេលអ្នករក្សាទុកប៉ុណ្ណោះ។",
        summaryCard: "សរុបការបញ្ជាទិញ",
        addItem: "បន្ថែមទំនិញ",
        addItemPlaceholder: "ស្វែងរកតាមឈ្មោះទំនិញ ឬ SKU…",
        noMatches: "រកមិនឃើញទំនិញទេ។",
        colItem: "ទំនិញ",
        colVariant: "ទំហំ / SKU",
        colPrice: "តម្លៃរាយ",
        colStock: "ស្តុកនៅសល់",
        colQty: "ចំនួន",
        colDiscount: "បញ្ចុះតម្លៃ",
        colSubtotal: "សរុប",
        colAction: "សកម្មភាព",
        emptyItems: "មិនទាន់មានទំនិញទេ — ស្វែងរកខាងលើដើម្បីបន្ថែម។",
        notEnoughStock: "មានតែ {qty} ប៉ុណ្ណោះ។",
        // ការបន្ថែមបរិមាណវាស់ជា DELTA ធៀបនឹងបរិមាណដែលគិតលុយបច្ចុប្បន្ន៖ ស្តុកគាំទ្រ
        // ចំនួនបន្ថែម ហើយសារបង្ហាញចំនួនដែលអាចបន្ថែមបាន និងដែនកំណត់អតិបរមា។
        raiseLimit:
          "អាចបន្ថែមបានតែ {qty} ទៀតប៉ុណ្ណោះ — ចំនួនសរុបអតិបរមាគឺ {max}។",
        // ទំនិញបន្ថែមគឺជាការទិញថ្មីក្នុងតម្លៃបច្ចុប្បន្ន — បង្ហាញពេលវាខុសពី
        // តម្លៃរបស់ជួរនេះ (ចំនួនសរុបគិតតាមរបៀបនេះរួចហើយ)។
        deltaPriceHint: "ទំនិញបន្ថែមគិតតម្លៃតាមតម្លៃបច្ចុប្បន្ន។",
        invalidQty: "សូមបញ្ចូលចំនួនគត់ ចាប់ពី ១ ឡើងទៅ។",
        belowHeld: "អតិថិជនកំពុងកាន់ {qty} — សូមប្រើការបង្វិលទំនិញវិញ។",
        discountTooBig: "លើសពីតម្លៃទំនិញនេះ។",
        priceRequired: "សូមបញ្ចូលតម្លៃ។",
        removeTitle: "ដកទំនិញនេះចេញ?",
        removeBody:
          "ទំនិញនឹងត្រឡប់ចូលស្តុកវិញពេលអ្នករក្សាទុក។ ជួរនេះនៅតែមាននៅក្នុងប្រវត្តិ។",
        removed: "បានដកចេញ",
        returnedSellable: "ប្រគល់មកវិញ · អាចលក់",
        returnedDamaged: "ប្រគល់មកវិញ · ខូច",
        pendingReturnSellable: "កំពុងប្រគល់មកវិញ · អាចលក់",
        pendingReturnDamaged: "កំពុងប្រគល់មកវិញ · ខូច",
        historicalReturn: "ប្រវត្តិប្រគល់មកវិញ · បានរក្សាទុកហើយ",
        pendingReturnStockIn: "ស្តុក +{qty} ពេលរក្សាទុក",
        undo: "ត្រឡប់វិញ",
        heldLocked: "នៅជាមួយអតិថិជន {qty}",
        newLine: "ថ្មី",
        // ទំនិញថ្មីដែលបន្ថែមលើការបញ្ជាទិញដែលបានបញ្ជូនរួច៖ របៀបដែលអតិថិជនទទួល។
        fulfillmentAsk: "តើអតិថិជនទទួលទំនិញថ្មីដោយរបៀបណា?",
        fulfillmentHandedNow: "ប្រគល់ឱ្យអតិថិជនឥឡូវនេះ",
        fulfillmentDeliverLater: "បញ្ជូននៅពេលក្រោយ",
        fulfillmentHandedNowHint: "ការបញ្ជាទិញនៅតែស្ថានភាព បានបញ្ជូនរួច។",
        fulfillmentDeliverLaterHint: "ការបញ្ជាទិញក្លាយជា បានបញ្ជូនមួយផ្នែក។",
        statusFollowsFulfillment: "ស្ថានភាពតាមរបៀបដែលអតិថិជនទទួលទំនិញថ្មី។",
        // សេចក្តីសង្ខេបនៃការបង្វិល/កែតម្រូវដែលកំពុងរង់ចាំ មុនពេលរក្សាទុក។
        changeSummaryTitle: "ការផ្លាស់ប្តូរនៅក្នុងការរក្សាទុកនេះ",
        changeSummaryNewItems: "ទំនិញចេញពីស្តុក",
        changeSummaryNetStock: "ស្តុកសុទ្ធ",
        changeSummaryMoney: "ប្រាក់",
        changeSummaryPrevTotal: "សរុបពីមុន",
        changeSummaryNewTotal: "សរុបថ្មី",
        changeSummaryAdditional: "ត្រូវបង់បន្ថែម",
        changeSummaryRefundDue: "ត្រូវបង្វិលប្រាក់",
        changeSummaryLessOwed: "ជំពាក់តិចជាងមុន",
        changeSummaryShippingChange: "ការផ្លាស់ប្តូរថ្លៃដឹកជញ្ជូន",
        changeSummaryShippingUnchanged: "ថ្លៃដឹកជញ្ជូនមិនផ្លាស់ប្តូរ",
        changeSummaryEmpty: "មិនទាន់មានការបង្វិល ឬកែតម្រូវទេ។",
        changeSummarySellable: "បង្វិលទៅស្តុកលក់វិញ",
        changeSummaryDamaged: "បានត្រឡប់ដោយខូចខាត",
        changeSummaryStill: "នៅជាមួយអតិថិជន",
        changeSummaryStillSuffix: "— នៅតែក្នុងវិក្ក័យបត្រ",
        changeSummaryIncorrect: "ការដឹកជញ្ជូនខុស",
        changeSummaryRefund: "ប្រាក់បង្វិល",
        changeSummaryUndo: "មិនធ្វើវិញ",
        resolveLine: "ដោះស្រាយ",
        cancelOrderAction: "លុបចោលការបញ្ជាទិញ",
        itemsSubtotal: "សរុបទំនិញ",
        stillOwed: "នៅជំពាក់",
        saveChanges: "រក្សាទុកការកែសម្រួល",
        saving: "កំពុងរក្សាទុក…",
        saved: "បានកែសម្រួលការបញ្ជាទិញ។",
        fixErrors: "សូមកែជួរដែលមានបញ្ហាមុននឹងរក្សាទុក។",
        noChanges: "មិនទាន់មានការផ្លាស់ប្តូរទេ។",
        unsavedTitle: "ចាកចេញដោយមិនរក្សាទុក?",
        unsavedBody: "ការកែសម្រួលរបស់អ្នកមិនទាន់បានរក្សាទុកទេ។",
        unsavedLeave: "ចាកចេញ",
        unsavedStay: "បន្តកែសម្រួល",
      },
    },
    // T17 — ទំព័ររាយការណ៍ដឹកជញ្ជូនពេលល្ងាច
    deliveryReport: {
      title: "របាយការណ៍ដឹកជញ្ជូន",
      hint: "កញ្ចប់យប់នេះ តម្រៀបតាមក្រុមហ៊ុនដឹកជញ្ជូន។ សម្គាល់លទ្ធផលនៃការបញ្ជាទិញនីមួយៗ ពីការបញ្ជាក់ដែលអ្នកបានទទួល — រូបថត ការហៅទូរស័ព្ទ ឬបញ្ជីក្រដាស។",
      openOrders: "កំពុងដឹកជញ្ជូន",
      markedToday: "បានសម្គាល់ថ្ងៃនេះ",
      markOutcome: "សម្គាល់លទ្ធផលដឹកជញ្ជូន",
      outcome: {
        delivered: "បានដឹកជូន",
        partial: "មួយផ្នែក",
        returned: "បានត្រឡប់មកវិញ",
        cancelled: "បានបោះបង់",
      },
      summary: {
        handled: "សរុបកញ្ចប់",
        delivered: "ដឹកជូន",
        partial: "មួយផ្នែក",
        returns: "ត្រឡប់មកវិញ",
        cancellations: "បោះបង់",
        feePayable: "ថ្លៃត្រូវបង់",
      },
      packagingPhoto: "រូបថតកញ្ចប់",
      uploadPhoto: "ផ្ទុករូបថត",
      photoUploaded: "បានរក្សាទុករូបថត។",
      deliveryOff:
        "ការដឹកជញ្ជូនបានបិទ។ បើកម៉ូឌុលដឹកជញ្ជូននៅក្នុងការកំណត់ហាង ដើម្បីប្រើទំព័រនេះ។",
      noOrders: "គ្មានកញ្ចប់ត្រូវសម្គាល់យប់នេះទេ — គ្មានការបញ្ជាទិញកំពុងដឹកជញ្ជូន។",
      partialTitle: "សម្គាល់ថាដឹកជូនមួយផ្នែក",
      partialHint:
        "តើអតិថិជនទទួលយកប៉ុន្មានដុំ? សល់នឹងត្រឡប់ចូលស្តុកវិញ។",
      mark: "សម្គាល់លទ្ធផល",
      outcomeMarked: "បានសម្គាល់លទ្ធផល។",
      feeUpdated: "បានធ្វើបច្ចុប្បន្នភាពថ្លៃដឹកជញ្ជូន។",
      selfDelivery: "ដឹកជញ្ជូនខ្លួនឯង",
      returnedConfirmTitle: "កញ្ចប់ទាំងមូលបានត្រឡប់មកវិញ?",
      returnedConfirmBody:
        "ទំនិញទាំងអស់នឹងត្រឡប់ចូលស្តុកវិញ។ ការបញ្ជាទិញត្រូវបានបោះបង់។",
      cancelledConfirmTitle: "បោះបង់ការដឹកជញ្ជូននេះ?",
      cancelledConfirmBody:
        "ទំនិញទាំងអស់នឹងត្រឡប់ចូលស្តុកវិញ។ ការបញ្ជាទិញត្រូវបានបោះបង់។",
    },
  },
} as const;
